---
title: "LabExercise2"
author: "Erikka Jane Parrenas"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(polite)
library(rvest)
library(dplyr)

url <- "https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm"

session <- bow(url, user_agent = "Educational purposes")
session

imdburl <- read_html(url)
```

```{r}
movie_title <- imdburl %>%
    html_nodes("h3.ipc-title__text") %>%
    html_text()

#subset for the movies. Taking 50 movie titles.
sub_movie <- movie_title[2:51]
(df_movie <- data.frame(Title = sub_movie))
```

```{r}
write.csv(df_movie, "IMDB50_Movies.csv")

read.csv("IMDB50_Movies.csv")
```


```{r}
library(polite)
library(rvest)

#1st movie url for the the name of the reviewer.
movie1_url <- "https://www.imdb.com/title/tt3359350/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov1 <- bow(movie1_url, user_agent = "educational purposes")

movie1 <- read_html(movie1_url)

movie1_url2 <- "https://www.imdb.com/title/tt3359350/reviews?sort=curated&dir=asc&ratingFilter=8"
session_Mov1_2 <- bow(movie1_url, user_agent = "educational purposes")

movie1_2 <- read_html(movie1_url2)
```

```{r}
#geting the 1st movie title to include it for the data frame.
first_title <- sub_movie[1]
first_title

#get the reviewer's name.
reviewer1 <- movie1 %>%
  html_nodes("span.display-name-link") %>%
  html_text()


#set as data frame
(df_reviewer1 <- data.frame(Name = reviewer1))
```

```{r}
#get the reviewer's name.
reviewer1_2 <- movie1_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()

#set as data frame
(df_reviewer1_2 <- data.frame(Name = reviewer1_2))
```

```{r}
#combining into one row the two data frame
(nameRev1 <- rbind(df_reviewer1,df_reviewer1_2))
```

```{r}
#get the the date of reviews
reviews_date1 <- movie1 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate1 <- data.frame(DateReview = reviews_date1))
```

```{r}
#get the the date of reviews
reviews_date1 <- movie1_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate1_2 <- data.frame(DateReview = reviews_date1))
```

```{r}
#combined the two data frame
(dateRev1 <- rbind(df_reviewsDate1, df_reviewsDate1_2))
```

```{r}
#get the user ratings
(reviews_rating1 <- movie1 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings
(sub_reviewsRating1 <- reviews_rating1[1:50])

#split the output to get on;y the rates without the \n.
(rate_split1 <- unlist(strsplit(sub_reviewsRating1, "\\s+")))

#select only the ratings to exclude the white space
(splitRate1 <- rate_split1[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])


#set as data frame
(df_rating1 <- data.frame (Rating = splitRate1))
```

```{r}
#get the user ratings
(reviews_rating1_2 <- movie1_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings
sub_reviewsRating1_2 <- reviews_rating1_2[1:50]
sub_reviewsRating1_2

#split the output to get on;y the rates without the \n.
rate_split1_2 <- unlist(strsplit(sub_reviewsRating1_2, "\\s+"))
rate_split1_2

#select only the ratings to exclude the white space
splitRate1_2 <- rate_split1_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)]
splitRate1_2

#set as data frame
df_rating1_2 <- data.frame (Rating = splitRate1_2)
df_rating1_2
```

```{r}
rating1 <- rbind(df_rating1,df_rating1_2) 
rating1
```

```{r}
#get the contents of the reviews.
review_text1 <- movie1 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText1 <- data.frame(TextReview = review_text1))
```

```{r}
#get the contents of the reviews.
review_text1_2 <- movie1_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText1_2 <- data.frame(TextReview = review_text1_2))
```

```{r}
#combined the two data frames in one row
(textRev1 <- rbind(df_reviewText1,df_reviewText1_2))
```

```{r}
#get the review title.
review_title1 <- movie1 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev1 <- review_title1[1:25])

(review_split1 <- unlist(strsplit(sub_titrev1, "\n")))

#set as data frame
(df_reviewTitle1 <- data.frame(TitleReview = review_split1))
```

```{r}
#get the review title.
review_title1_2 <- movie1_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev1_2 <- review_title1_2[1:25])

(review_split1_2 <- unlist(strsplit(sub_titrev1_2, "\n")))

#set as data frame
(df_reviewTitle1_2 <- data.frame(TitleReview = review_split1_2))
```

```{r}
(titleRev1 <- rbind(df_reviewTitle1, df_reviewTitle1_2))
```

```{r}
#combined the outputs of the first movie in a data frame
df_movie1 <- data.frame(Title = first_title,
                        nameRev1,
                        rating1,                    
                        dateRev1,
                        textRev1,
                        titleRev1
                       )
df_movie1
```

```{r}
library(polite)
library(rvest)

#2nd movie url for the the name of the reviewer.
movie2_url <- "https://www.imdb.com/title/tt15239678/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov2 <- bow(movie1_url, user_agent = "educational purposes")

movie2 <- read_html(movie2_url)

movie2_url2 <- "https://www.imdb.com/title/tt15239678/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov2_2 <- bow(movie2_url, user_agent = "educational purposes")

movie2_2 <- read_html(movie2_url2)
```

```{r}
#geting the 2nd movie title to include it for the data frame.
(second_title <- sub_movie[2])

#get the reviewer's name.
(reviewer2 <- movie2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer2 <- data.frame(Name = reviewer2))

```

```{r}
#get the reviewer's name.
(reviewer2_2 <- movie2_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer2_2 <- data.frame(Name = reviewer2_2))
```

```{r}
(nameRev2 <- rbind(df_reviewer2,df_reviewer2_2))
```

```{r}
#get the the date of reviews
reviews_date2 <- movie2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate2 <- data.frame(DateReview = reviews_date2))
```

```{r}
#get the the date of reviews
reviews_date2_2 <- movie2_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate2_2 <- data.frame(DateReview = reviews_date2_2))
```

```{r}
(dateRev2 <- rbind(df_reviewsDate2, df_reviewsDate2_2))
```

```{r}
#get the user ratings
reviews_rating2 <- movie2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings to get only 25
(sub_reviewsRating2 <- reviews_rating2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split2 <- unlist(strsplit(sub_reviewsRating2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate2 <- rate_split2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating2 <- data.frame (Rating = splitRate2))
```

```{r}
#get the user ratings
reviews_rating2_2 <- movie2_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings to get only 25
(sub_reviewsRating2_2 <- reviews_rating2_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split2_2 <- unlist(strsplit(sub_reviewsRating2_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate2_2 <- rate_split2_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating2_2 <- data.frame (Rating = splitRate2_2))
```

```{r}
(rating2 <- rbind(df_rating2,df_rating2_2))
```

```{r}
#get the contents of the reviews.
(review_text2 <- movie2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText2 <- data.frame(TextReview = review_text2))
```

```{r}
#get the contents of the reviews.
(review_text2_2 <- movie2_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

(sub_textrev2_2 <- review_text2_2[1:25])

#set as data frame.
(df_reviewText2_2 <- data.frame(TextReview = sub_textrev2_2))
```


```{r}
textRev2 <- rbind(df_reviewText2,df_reviewText2_2) 
textRev2
```

```{r}
#get the review title.
review_title2 <- movie2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title2

#subset the review title get only 25
sub_titrev2 <- review_title2[1:25]
sub_titrev2


review_split2 <- unlist(strsplit(sub_titrev2, "\n"))
review_split2

#set as data frame
df_reviewTitle2 <- data.frame(TitleReview = review_split2)
df_reviewTitle2
```

```{r}
#get the review title.
review_title2_2 <- movie2_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title2_2

#subset the review title get only 25
sub_titrev2_2 <- review_title2_2[1:25]
sub_titrev2_2

review_split2_2 <- unlist(strsplit(sub_titrev1_2, "\n"))
review_split2_2

#set as data frame
df_reviewTitle2_2 <- data.frame(TitleReview = review_split2_2)
df_reviewTitle2_2
```

```{r}
titleRev2 <- rbind(df_reviewTitle2, df_reviewTitle2_2)
titleRev2
```

```{r}
#combined the outputs of the first movie in a data frame
df_movie2 <- data.frame(Title = second_title,
                        nameRev2,
                        rating2,                    
                        dateRev2,
                        textRev2,
                        titleRev2
                       )
df_movie2
```

```{r}
#combined the movie1 and movie2
moviesRev12 <- rbind(df_movie1, df_movie2)
moviesRev12
```

```{r}
library(readr)
write.csv(moviesRev12, "IMDBmoviesReviews(1st_100).csv")

read.csv("IMDBmoviesReviews(1st_100).csv")
```

```{r}
library(polite)
library(rvest)

#3rd movie url for the the name of the reviewer.
movie3_url <- "https://www.imdb.com/title/tt14539740/reviews?sort=curated&dir=asc&ratingFilter=10"
session_Mov3 <- bow(movie3_url, user_agent = "educational purposes")

movie3<- read_html(movie3_url)

movie3_url2 <- "https://www.imdb.com/title/tt14539740/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov3_2 <- bow(movie3_url2, user_agent = "educational purposes")

movie3_2 <- read_html(movie3_url2)
```

```{r}
#geting the 3rd movie title to include it for the data frame.
(third_title <- sub_movie[3])

#get the reviewer's name.
reviewer3 <- movie3 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer3


#set as data frame
(df_reviewer3 <- data.frame(Name = reviewer3))

```

```{r}
#get the reviewer's name.
reviewer3_2 <- movie3_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer3_2

#set as data frame
(df_reviewer3_2 <- data.frame(Name = reviewer3_2))
```

```{r}
#combine into one row
(nameRev3 <- rbind(df_reviewer3,df_reviewer3_2)) 
```

```{r}
#get the the date of reviews
reviews_date3 <- movie3 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate3 <- data.frame(DateReview = reviews_date3))
```

```{r}
#get the the date of reviews
reviews_date3_2 <- movie3_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate3_2 <- data.frame(DateReview = reviews_date3_2))
```

```{r}
(dateRev3 <- rbind(df_reviewsDate3, df_reviewsDate3_2)) 
```

```{r}
#get the user ratings
reviews_rating3 <- movie3 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating3

#subset the ratings to get only 25
(sub_reviewsRating3 <- reviews_rating3[1:50])

#split the output to get on;y the rates without the \n.
(rate_split3 <- unlist(strsplit(sub_reviewsRating3, "\\s+")))

#select only the ratings to exclude the white space
(splitRate3 <- rate_split3[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating3 <- data.frame (Rating = splitRate3))
```

```{r}
#get the user ratings
reviews_rating3_2 <- movie3_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating3_2

#subset the ratings to get only 25
(sub_reviewsRating3_2 <- reviews_rating3_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split3_2 <- unlist(strsplit(sub_reviewsRating3_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate3_2 <- rate_split3_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating3_2 <- data.frame (Rating = splitRate3_2))
```

```{r}
#combine into one row
(rating3 <- rbind(df_rating3,df_rating3_2))
```

```{r}
#get the contents of the reviews
review_text3 <- movie3 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text3

#set as data frame.
(df_reviewText3 <- data.frame(TextReview = review_text3))
```

```{r}
#get the contents of the reviews
review_text3_2 <- movie3_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text3_2

#set as data frame.
(df_reviewText3_2 <- data.frame(TextReview = review_text3_2))

(textRev3 <- rbind(df_reviewText3,df_reviewText3_2))
```

```{r}
#get the review title.
review_title3 <- movie3 %>%
  html_nodes("a.title") %>%
  html_text()
review_title3

#subset the review title get only 25
(sub_titrev3 <- review_title3[1:25])

(review_split3 <- unlist(strsplit(sub_titrev3, "\n")))

#set as data frame
(df_reviewTitle3 <- data.frame(TitleReview = review_split3))
```

```{r}
#get the review title.
review_title3_2 <- movie3_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title3_2

#subset the review title get only 25
(sub_titrev3_2 <- review_title3_2[1:25])

(review_split3_2 <- unlist(strsplit(sub_titrev3_2, "\n")))
#set as data frame
(df_reviewTitle3_2 <- data.frame(TitleReview = review_split3_2))
```

```{r}
(titleRev3 <- rbind(df_reviewTitle3, df_reviewTitle3_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie3 <- data.frame(Title = third_title,
                        nameRev3,
                        rating3,                    
                        dateRev3,
                        textRev3,
                        titleRev3)
)
```

```{r}
library(polite)
library(rvest)

#4th movie url for the the name of the reviewer.
movie4_url <- "https://www.imdb.com/title/tt21235248/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov4 <- bow(movie4_url, user_agent = "educational purposes")

movie4 <- read_html(movie4_url)

movie4_url2 <- "https://www.imdb.com/title/tt21235248/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov4_2 <- bow(movie4_url2, user_agent = "educational purposes")

movie4_2 <- read_html(movie4_url2)
```

```{r}
#geting the 4th movie title to include it for the data frame.
(fourth_title <- sub_movie[4])

#get the reviewer's name.
(reviewer4 <- movie4 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer4 <- data.frame(Name = reviewer4))
```

```{r}
#get the reviewer's name.
(reviewer4_2 <- movie4_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer4_2 <- data.frame(Name = reviewer4_2))
```

```{r}
#combine the output into one row
(nameRev4 <- rbind(df_reviewer4,df_reviewer4_2))
```

```{r}
#get the the date of reviews
reviews_date4 <- movie4 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate4 <- data.frame(DateReview = reviews_date4))
```

```{r}
#get the the date of reviews
reviews_date4_2 <- movie4_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate4_2 <- data.frame(DateReview = reviews_date4_2))
```

```{r}
#combine the output into one row
(dateRev4 <- rbind(df_reviewsDate4, df_reviewsDate4_2))
```

```{r}
#get the user ratings
reviews_rating4 <- movie4 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings to get only 25
(sub_reviewsRating4 <- reviews_rating4[1:50])

#split the output to get on;y the rates without the \n.
(rate_split4 <- unlist(strsplit(sub_reviewsRating4, "\\s+")))

#select only the ratings to exclude the white space
(splitRate4 <- rate_split4[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating4 <- data.frame (Rating = splitRate4))
```

```{r}
#get the user ratings
reviews_rating4_2 <- movie4_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings to get only 25
(sub_reviewsRating4_2 <- reviews_rating4_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split4_2 <- unlist(strsplit(sub_reviewsRating4_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate4_2 <- rate_split4_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating4_2 <- data.frame (Rating = splitRate4_2))
```

```{r}
#combine into one row
(rating4 <- rbind(df_rating4,df_rating4_2))
```

```{r}
#get the contents of the reviews
review_text4 <- movie4 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text4

#set as data frame.
(df_reviewText4 <- data.frame(TextReview = review_text4))
```

```{r}
#get the contents of the reviews
review_text4_2 <- movie4_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text4_2

#set as data frame.
(df_reviewText4_2 <- data.frame(TextReview = review_text4_2))

#combine into one frame
(textRev4 <- rbind(df_reviewText4,df_reviewText4_2))
```

```{r}
#get the review title.
review_title4 <- movie4 %>%
  html_nodes("a.title") %>%
  html_text()
review_title4

#subset the review title get only 25
(sub_titrev4 <- review_title4[1:25])

(review_split4 <- unlist(strsplit(sub_titrev4, "\n")))

#set as data frame
(df_reviewTitle4 <- data.frame(TitleReview = review_split4))
```

```{r}
#get the review title.
review_title4_2 <- movie4_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title4_2

#subset the review title get only 25
(sub_titrev4_2 <- review_title4_2[1:25])

(review_split4_2 <- unlist(strsplit(sub_titrev4_2, "\n")))

#set as data frame
(df_reviewTitle4_2 <- data.frame(TitleReview = review_split4_2))

#combine into one row
(titleRev4 <- rbind(df_reviewTitle4, df_reviewTitle4_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie4 <- data.frame(Title = fourth_title,
                        nameRev4,
                        rating4,                    
                        dateRev4,
                        textRev4,
                        titleRev4)
)
```

```{r}
library(polite)
library(rvest)

#5th movie url for the the name of the reviewer.
movie5_url <- "https://www.imdb.com/title/tt14230458/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov5 <- bow(movie5_url, user_agent = "educational purposes")

movie5 <- read_html(movie5_url)

movie5_url2 <- "https://www.imdb.com/title/tt14230458/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov5_2 <- bow(movie5_url2, user_agent = "educational purposes")

movie5_2 <- read_html(movie5_url2)
```

```{r}
#geting the 5th movie title to include it for the data frame.
(fifth_title <- sub_movie[5])

#get the reviewer's name.
reviewer5 <- movie5 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer5

#set as data frame
(df_reviewer5 <- data.frame(Name = reviewer5))
```

```{r}
#get the reviewer's name.
reviewer5_2 <- movie5_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer5_2

#set as data frame
(df_reviewer5_2 <- data.frame(Name = reviewer5_2))
```

```{r}
#combine the output into one row
(nameRev5 <- rbind(df_reviewer5,df_reviewer5_2))
```

```{r}
#get the the date of reviews
reviews_date5 <- movie4 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate5 <- data.frame(DateReview = reviews_date5))
```

```{r}
#get the the date of reviews
reviews_date5_2 <- movie5_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate5_2 <- data.frame(DateReview = reviews_date5_2))

#combine the output into one row
(dateRev5 <- rbind(df_reviewsDate5, df_reviewsDate5_2))
```

```{r}
#get the user ratings
reviews_rating5 <- movie5 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating5

#subset the ratings to get only 25
(sub_reviewsRating5 <- reviews_rating5[1:50])

#split the output to get on;y the rates without the \n.
(rate_split5 <- unlist(strsplit(sub_reviewsRating5, "\\s+")))

#select only the ratings to exclude the white space
(splitRate5 <- rate_split5[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating5 <- data.frame (Rating = splitRate5))
```

```{r}
#get the user ratings
reviews_rating5_2 <- movie5_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating5_2

#subset the ratings to get only 25
(sub_reviewsRating5_2 <- reviews_rating5_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split5_2 <- unlist(strsplit(sub_reviewsRating5_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate5_2 <- rate_split5_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating5_2 <- data.frame (Rating = splitRate5_2))
```

```{r}
#combine into one row
(rating5 <- rbind(df_rating5,df_rating5_2))
```

```{r}
#get the contents of the reviews
review_text5 <- movie4 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text5

#set as data frame.
(df_reviewText5 <- data.frame(TextReview = review_text5))
```

```{r}
#get the contents of the reviews
review_text5_2 <- movie5_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text5_2

#set as data frame.
(df_reviewText5_2 <- data.frame(TextReview = review_text5_2))
```

```{r}
#combine into one frame
(textRev5 <- rbind(df_reviewText5,df_reviewText5_2))
```

```{r}
#get the review title.
review_title5 <- movie5 %>%
  html_nodes("a.title") %>%
  html_text()
review_title5

#subset the review title get only 25
(sub_titrev5 <- review_title5[1:25])

(review_split5 <- unlist(strsplit(sub_titrev5, "\n")))

#set as data frame
(df_reviewTitle5 <- data.frame(TitleReview = review_split5))
```

```{r}
#get the review title.
review_title5_2 <- movie5_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title5_2

#subset the review title get only 25
(sub_titrev5_2 <- review_title5_2[1:25])

(review_split5_2 <- unlist(strsplit(sub_titrev5_2, "\n")))

#set as data frame
(df_reviewTitle5_2 <- data.frame(TitleReview = review_split5_2))
```

```{r}
#combine into one row
(titleRev5 <- rbind(df_reviewTitle5, df_reviewTitle5_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie5 <- data.frame(Title = fifth_title,
                        nameRev5,
                        rating5,                    
                        dateRev5,
                        textRev5,
                        titleRev5)
)
```

```{r}
library(polite)
library(rvest)

#6th movie url for the the name of the reviewer.
movie6_url <- "https://www.imdb.com/title/tt0098206/reviews?sort=curated&dir=desc&ratingFilter=9"
session_Mov6 <- bow(movie6_url, user_agent = "educational purposes")

movie6 <- read_html(movie6_url)

movie6_url2 <- "https://www.imdb.com/title/tt0098206/reviews?sort=curated&dir=desc&ratingFilter=10"
session_Mov6_2 <- bow(movie6_url, user_agent = "educational purposes")

movie6_2 <- read_html(movie6_url2)
```

```{r}
#geting the 6th movie title to include it for the data frame.
(sixth_title <- sub_movie[6])

#get the reviewer's name.
reviewer6 <- movie6 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer6

#set as data frame
(df_reviewer6 <- data.frame(Name = reviewer6))
```

```{r}
#get the reviewer's name.
reviewer6_2 <- movie6_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer6_2

#set as data frame
(df_reviewer6_2 <- data.frame(Name = reviewer6_2))
```

```{r}
#combine the output into one row
(nameRev6 <- rbind(df_reviewer6,df_reviewer6_2))
```

```{r}
#get the the date of reviews
reviews_date6 <- movie6 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate6 <- data.frame(DateReview = reviews_date6))
```

```{r}
#get the the date of reviews
reviews_date6_2 <- movie6_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate6_2 <- data.frame(DateReview = reviews_date6_2))
```

```{r}
#combine the output into one row
(dateRev6 <- rbind(df_reviewsDate6, df_reviewsDate6_2))
```

```{r}
#get the user ratings
reviews_rating6 <- movie6 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating6

#subset the ratings to get only 25
(sub_reviewsRating6 <- reviews_rating6[1:50])

#split the output to get on;y the rates without the \n.
(rate_split6 <- unlist(strsplit(sub_reviewsRating6, "\\s+")))

#select only the ratings to exclude the white space
(splitRate6 <- rate_split6[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating6 <- data.frame (Rating = splitRate6))
```

```{r}
#get the user ratings
reviews_rating6_2 <- movie6_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating6_2

#subset the ratings to get only 25
(sub_reviewsRating6_2 <- reviews_rating6_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split6_2 <- unlist(strsplit(sub_reviewsRating6_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate6_2 <- rate_split6_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating6_2 <- data.frame (Rating = splitRate6_2))
```

```{r}
#combine into one row
(rating6 <- rbind(df_rating6,df_rating6_2))
```

```{r}
#get the contents of the reviews
review_text6 <- movie6 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text6

#set as data frame.
(df_reviewText6 <- data.frame(TextReview = review_text6))
```


```{r}
#get the contents of the reviews
review_text6_2 <- movie6_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text6_2

#set as data frame.
(df_reviewText6_2 <- data.frame(TextReview = review_text6_2))
```

```{r}
#combine into one frame
(textRev6 <- rbind(df_reviewText6,df_reviewText6_2))
```

```{r}
#get the review title.
review_title6 <- movie6 %>%
  html_nodes("a.title") %>%
  html_text()
review_title6

#subset the review title get only 25
(sub_titrev6 <- review_title6[1:25])

(review_split6 <- unlist(strsplit(sub_titrev6, "\n")))

#set as data frame
(df_reviewTitle6 <- data.frame(TitleReview = review_split6))
```

```{r}
#get the review title.
review_title6_2 <- movie6_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title6_2

#subset the review title get only 25
(sub_titrev6_2 <- review_title6_2[1:25])

(review_split6_2 <- unlist(strsplit(sub_titrev6_2, "\n")))

#set as data frame
(df_reviewTitle6_2 <- data.frame(TitleReview = review_split6_2))
```

```{r}
#combine into one row
(titleRev6 <- rbind(df_reviewTitle6, df_reviewTitle6_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie6 <- data.frame(Title = sixth_title,
                        nameRev6,
                        rating6,                    
                        dateRev6,
                        textRev6,
                        titleRev6)
)
```

```{r}
#combined data frames into one row 
moviesRev3456 <- rbind(df_movie3, df_movie4, df_movie5, df_movie6)
moviesRev3456
```


```{r}
library(readr)
write.csv(moviesRev3456, "IMDBmoviesReviews(2nd_200).csv")

read.csv("IMDBmoviesReviews(2nd_200).csv")
```

```{r}
library(polite)
library(rvest)

#7th movie url for the the name of the reviewer.
movie7_url <- "https://www.imdb.com/title/tt23137390/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov7 <- bow(movie7_url, user_agent = "educational purposes")

movie7 <- read_html(movie7_url)

movie7_url2 <- "https://www.imdb.com/title/tt23137390/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov7_2 <- bow(movie7_url2, user_agent = "educational purposes")

movie7_2 <- read_html(movie7_url2)
```

```{r}
#geting the 7th movie title to include it for the data frame.
(seventh_title <- sub_movie[8])

#get the reviewer's name.
reviewer7 <- movie7 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer7

#set as data frame
(df_reviewer7 <- data.frame(Name = reviewer7))
```

```{r}
#get the reviewer's name.
reviewer7_2 <- movie7_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer7_2

#set as data frame
(df_reviewer7_2 <- data.frame(Name = reviewer7_2))
```

```{r}
#combine into one row
(nameRev7 <- rbind(df_reviewer7, df_reviewer7_2)) 
```

```{r}
#get the the date of reviews
reviews_date7 <- movie7 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate7 <- data.frame(DateReview = reviews_date7))
```

```{r}
#get the the date of reviews
reviews_date7_2 <- movie7_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate7_2 <- data.frame(DateReview = reviews_date7_2))
```

```{r}
#combine into one row
(dateRev7 <- rbind(df_reviewsDate7, df_reviewsDate7_2)) 
```

```{r}
#get the user ratings
reviews_rating7 <- movie7 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating7

#subset the ratings to get only 25
(sub_reviewsRating7 <- reviews_rating7[1:50])

#split the output to get on;y the rates without the \n.
(rate_split7 <- unlist(strsplit(sub_reviewsRating7, "\\s+")))

#select only the ratings to exclude the white space
(splitRate7 <- rate_split7[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating7 <- data.frame (Rating = splitRate7))
```

```{r}
#get the user ratings
reviews_rating7_2 <- movie7_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating7_2

#subset the ratings to get only 25
(sub_reviewsRating7_2 <- reviews_rating7_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split7_2 <- unlist(strsplit(sub_reviewsRating7_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate7_2 <- rate_split7_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating7_2 <- data.frame (Rating = splitRate7_2))
```

```{r}
#combine into one row
(rating7 <- rbind(df_rating7,df_rating7_2))
```

```{r}
#get the contents of the reviews
review_text7 <- movie7 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text7

#set as data frame.
(df_reviewText7 <- data.frame(TextReview = review_text7))
```

```{r}
#get the contents of the reviews
review_text7_2 <- movie7_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text7_2

#set as data frame.
(df_reviewText7_2 <- data.frame(TextReview = review_text7_2))
```

```{r}
#cobine into one row
(textRev7 <- rbind(df_reviewText7, df_reviewText7_2))
```

```{r}
#get the review title.
review_title7 <- movie7 %>%
  html_nodes("a.title") %>%
  html_text()
review_title7

#subset the review title get only 25
(sub_titrev7 <- review_title7[1:25])

(review_split7 <- unlist(strsplit(sub_titrev7, "\n")))

#set as data frame
(df_reviewTitle7 <- data.frame(TitleReview = review_split7))
```

```{r}
#get the review title.
review_title7_2 <- movie7_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title7_2

#subset the review title get only 25
(sub_titrev7_2 <- review_title7_2[1:25])

(review_split7_2 <- unlist(strsplit(sub_titrev7_2, "\n")))
#set as data frame
(df_reviewTitle7_2 <- data.frame(TitleReview = review_split7_2))
```

```{r}
(titleRev7 <- rbind(df_reviewTitle7, df_reviewTitle7_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie7 <- data.frame(Title = seventh_title,
                        nameRev7,
                        rating7,                    
                        dateRev7,
                        textRev7,
                        titleRev7)
)
```

```{r}
library(polite)
library(rvest)

#8th movie url for the the name of the reviewer.
movie8_url <- "https://www.imdb.com/title/tt15398776/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov8 <- bow(movie8_url, user_agent = "educational purposes")

movie8 <- read_html(movie8_url)

movie8_url2 <- "https://www.imdb.com/title/tt15398776/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov8_2 <- bow(movie8_url2, user_agent = "educational purposes")

movie8_2 <- read_html(movie8_url2)
```

```{r}
#geting the 8th movie title to include it for the data frame.
(eight_title <- sub_movie[9])

#get the reviewer's name.
reviewer8 <- movie8 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer8

#set as data frame
(df_reviewer8 <- data.frame(Name = reviewer8))
```

```{r}
#get the reviewer's name.
reviewer8_2 <- movie8_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer8_2

#set as data frame
(df_reviewer8_2 <- data.frame(Name = reviewer8_2))
```

```{r}
#combine the output into one row
(nameRev8 <- rbind(df_reviewer8,df_reviewer8_2))
```

```{r}
#get the the date of reviews
reviews_date8 <- movie8 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate8 <- data.frame(DateReview = reviews_date8))
```

```{r}
#get the the date of reviews
reviews_date8_2 <- movie8_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate8_2 <- data.frame(DateReview = reviews_date8_2))
```

```{r}
#combine the output into one row
(dateRev8 <- rbind(df_reviewsDate8, df_reviewsDate8_2))
```

```{r}
#get the user ratings
reviews_rating8 <- movie8 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings to get only 25
(sub_reviewsRating8 <- reviews_rating8[1:50])

#split the output to get on;y the rates without the \n.
(rate_split8 <- unlist(strsplit(sub_reviewsRating8, "\\s+")))

#select only the ratings to exclude the white space
(splitRate8 <- rate_split8[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating8 <- data.frame (Rating = splitRate8))
```

```{r}
#get the user ratings
reviews_rating8_2 <- movie8_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings to get only 25
(sub_reviewsRating8_2 <- reviews_rating8_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split8_2 <- unlist(strsplit(sub_reviewsRating8_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate8_2 <- rate_split8_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating8_2 <- data.frame (Rating = splitRate8_2))
```

```{r}
#combine into one row
(rating8 <- rbind(df_rating4,df_rating8_2))
```

```{r}
#get the contents of the reviews
review_text8 <- movie8 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text8

#set as data frame.
(df_reviewText8 <- data.frame(TextReview = review_text8))
```

```{r}
#get the contents of the reviews
review_text8_2 <- movie8_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text8_2

#set as data frame.
(df_reviewText8_2 <- data.frame(TextReview = review_text8_2))
```

```{r}
#combine into one frame
(textRev8 <- rbind(df_reviewText8,df_reviewText8_2))
```

```{r}
#get the review title.
review_title8 <- movie8 %>%
  html_nodes("a.title") %>%
  html_text()
review_title8

#subset the review title get only 25
(sub_titrev8 <- review_title8[1:25])

(review_split8 <- unlist(strsplit(sub_titrev8, "\n")))

#set as data frame
(df_reviewTitle8 <- data.frame(TitleReview = review_split8))
```

```{r}
#get the review title.
review_title8_2 <- movie8_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title8_2

#subset the review title get only 25
(sub_titrev8_2 <- review_title8_2[1:25])

(review_split8_2 <- unlist(strsplit(sub_titrev8_2, "\n")))

#set as data frame
(df_reviewTitle8_2 <- data.frame(TitleReview = review_split8_2))
```

```{r}
#combine into one row
(titleRev8 <- rbind(df_reviewTitle8, df_reviewTitle8_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie8 <- data.frame(Title = eight_title,
                        nameRev8,
                        rating8,                    
                        dateRev8,
                        textRev8,
                        titleRev8)
)
```

```{r}
library(polite)
library(rvest)

#9th movie url for the the name of the reviewer.
movie9_url <- "https://www.imdb.com/title/tt13452446/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov9 <- bow(movie9_url, user_agent = "educational purposes")

movie9 <- read_html(movie9_url)

movie9_url2 <- "https://www.imdb.com/title/tt13452446/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov9_2 <- bow(movie9_url2, user_agent = "educational purposes")

movie9_2 <- read_html(movie9_url2)
```

```{r}
#geting the 9th movie title to include it for the data frame.
(nineth_title <- sub_movie[10])

#get the reviewer's name.
reviewer9 <- movie9 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer9

#set as data frame
(df_reviewer9 <- data.frame(Name = reviewer9))
```

```{r}
#get the reviewer's name.
reviewer9_2 <- movie9_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer9_2

#set as data frame
(df_reviewer9_2 <- data.frame(Name = reviewer9_2))
```

```{r}
#combine the output into one row
(nameRev9 <- rbind(df_reviewer9,df_reviewer9_2))
```

```{r}
#get the the date of reviews
reviews_date9 <- movie9 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate9 <- data.frame(DateReview = reviews_date9))
```

```{r}
#get the the date of reviews
reviews_date9_2 <- movie9_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate9_2 <- data.frame(DateReview = reviews_date9_2))

#combine the output into one row
(dateRev9 <- rbind(df_reviewsDate9, df_reviewsDate9_2))
```

```{r}
#get the user ratings
reviews_rating9 <- movie9 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating9

#subset the ratings to get only 25
(sub_reviewsRating9 <- reviews_rating5[1:50])

#split the output to get on;y the rates without the \n.
(rate_split9 <- unlist(strsplit(sub_reviewsRating5, "\\s+")))

#select only the ratings to exclude the white space
(splitRate9 <- rate_split9[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating9 <- data.frame (Rating = splitRate9))
```

```{r}
#get the user ratings
reviews_rating9_2 <- movie9_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating9_2

#subset the ratings to get only 25
(sub_reviewsRating9_2 <- reviews_rating9_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split9_2 <- unlist(strsplit(sub_reviewsRating9_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate9_2 <- rate_split9_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating9_2 <- data.frame (Rating = splitRate9_2))
```

```{r}
#combine into one row
(rating9 <- rbind(df_rating9,df_rating9_2))
```

```{r}
#get the contents of the reviews
review_text9 <- movie9 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text9

#set as data frame.
(df_reviewText9 <- data.frame(TextReview = review_text9))
```

```{r}
#get the contents of the reviews
review_text9_2 <- movie9_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text9_2

#set as data frame.
(df_reviewText9_2 <- data.frame(TextReview = review_text9_2))
```

```{r}
#combine into one frame
(textRev9 <- rbind(df_reviewText9,df_reviewText9_2))
```

```{r}
#get the review title.
review_title9 <- movie9 %>%
  html_nodes("a.title") %>%
  html_text()
review_title9

#subset the review title get only 25
(sub_titrev9 <- review_title5[1:25])

(review_split9 <- unlist(strsplit(sub_titrev9, "\n")))

#set as data frame
(df_reviewTitle9 <- data.frame(TitleReview = review_split9))
```

```{r}
#get the review title.
review_title9_2 <- movie9_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title9_2

#subset the review title get only 25
(sub_titrev9_2 <- review_title9_2[1:25])

(review_split9_2 <- unlist(strsplit(sub_titrev9_2, "\n")))

#set as data frame
(df_reviewTitle9_2 <- data.frame(TitleReview = review_split9_2))
```

```{r}
#combine into one row
(titleRev9 <- rbind(df_reviewTitle9, df_reviewTitle9_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie9 <- data.frame(Title = nineth_title,
                        nameRev9,
                        rating9,                    
                        dateRev9,
                        textRev9,
                        titleRev9)
)
```

```{r}
library(polite)
library(rvest)

#10th movie url for the the name of the reviewer.
movie10_url <- "https://www.imdb.com/title/tt15398776/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov10 <- bow(movie10_url, user_agent = "educational purposes")

movie10 <- read_html(movie10_url)

movie10_url2 <- "https://www.imdb.com/title/tt15398776/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov10_2 <- bow(movie10_url, user_agent = "educational purposes")

movie10_2 <- read_html(movie10_url2)
```

```{r}
#geting the 10th movie title to include it for the data frame.
(tenth_title <- sub_movie[11])

#get the reviewer's name.
reviewer10 <- movie10 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer10

#set as data frame
(df_reviewer10 <- data.frame(Name = reviewer10))
```

```{r}
#get the reviewer's name.
reviewer10_2 <- movie10_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer10_2

#set as data frame
(df_reviewer10_2 <- data.frame(Name = reviewer10_2))
```

```{r}
#combine the output into one row
(nameRev10 <- rbind(df_reviewer10,df_reviewer10_2))
```

```{r}
#get the the date of reviews
reviews_date10 <- movie10 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate10 <- data.frame(DateReview = reviews_date10))
```

```{r}
#get the the date of reviews
reviews_date10_2 <- movie10_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate10_2 <- data.frame(DateReview = reviews_date10_2))
```

```{r}
#combine the output into one row
(dateRev10 <- rbind(df_reviewsDate10, df_reviewsDate10_2))
```

```{r}
#get the user ratings
reviews_rating10 <- movie10 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating10

#subset the ratings to get only 25
(sub_reviewsRating10 <- reviews_rating10[1:50])

#split the output to get on;y the rates without the \n.
(rate_split10 <- unlist(strsplit(sub_reviewsRating10, "\\s+")))

#select only the ratings to exclude the white space
(splitRate10 <- rate_split10[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating10 <- data.frame (Rating = splitRate6))
```

```{r}
#get the user ratings
reviews_rating10_2 <- movie10_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating10_2

#subset the ratings to get only 25
(sub_reviewsRating10_2 <- reviews_rating10_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split10_2 <- unlist(strsplit(sub_reviewsRating10_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate10_2 <- rate_split10_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating10_2 <- data.frame (Rating = splitRate10_2))
```

```{r}
#combine into one row
(rating10 <- rbind(df_rating10,df_rating10_2))
```

```{r}
#get the contents of the reviews
review_text10 <- movie10 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text10

#set as data frame.
(df_reviewText10 <- data.frame(TextReview = review_text10))
```


```{r}
#get the contents of the reviews
review_text10_2 <- movie10_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text10_2

#set as data frame.
(df_reviewText10_2 <- data.frame(TextReview = review_text10_2))
```

```{r}
#combine into one frame
(textRev10 <- rbind(df_reviewText10,df_reviewText10_2))
```

```{r}
#get the review title.
review_title10 <- movie10 %>%
  html_nodes("a.title") %>%
  html_text()
review_title10

#subset the review title get only 25
(sub_titrev10 <- review_title10[1:25])

(review_split10 <- unlist(strsplit(sub_titrev10, "\n")))

#set as data frame
(df_reviewTitle10 <- data.frame(TitleReview = review_split10))
```

```{r}
#get the review title.
review_title10_2 <- movie10_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title10_2

#subset the review title get only 25
(sub_titrev10_2 <- review_title10_2[1:25])

(review_split10_2 <- unlist(strsplit(sub_titrev10_2, "\n")))

#set as data frame
(df_reviewTitle10_2 <- data.frame(TitleReview = review_split10_2))
```

```{r}
#combine into one row
(titleRev10 <- rbind(df_reviewTitle10, df_reviewTitle10_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie10 <- data.frame(Title = tenth_title,
                        nameRev10,
                        rating10,                    
                        dateRev10,
                        textRev10,
                        titleRev10)
)
```

```{r}
moviesRev78910 <- rbind(df_movie7, df_movie8, df_movie9, df_movie10)
moviesRev78910
```


```{r}
write.csv(moviesRev78910, "IMDBmoviesReviews(3rd_200).csv")

read.csv("IMDBmoviesReviews(3rd_200).csv")
```

```{r}
library(polite)
library(rvest)

#11th movie url for the the name of the reviewer.
movie11_url <- "https://www.imdb.com/title/tt14966898/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov11 <- bow(movie11_url, user_agent = "educational purposes")

movie11 <- read_html(movie11_url)

movie11_url2 <- "https://www.imdb.com/title/tt14966898/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov11_2 <- bow(movie11_url2, user_agent = "educational purposes")

movie11_2 <- read_html(movie11_url2)
```

```{r}
#geting the 11th movie title to include it for the data frame.
(eleventh_title <- sub_movie[12])

#get the reviewer's name.
reviewer11 <- movie11 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer11

#set as data frame
(df_reviewer11 <- data.frame(Name = reviewer11))
```

```{r}
#get the reviewer's name.
reviewer11_2 <- movie11_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer11_2

#set as data frame
(df_reviewer11_2 <- data.frame(Name = reviewer11_2))
```

```{r}
#combine into one row
(nameRev11 <- rbind(df_reviewer11, df_reviewer11_2)) 
```

```{r}
#get the the date of reviews
reviews_date11 <- movie11 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate11 <- data.frame(DateReview = reviews_date11))
```

```{r}
#get the the date of reviews
reviews_date11_2 <- movie11_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate11_2 <- data.frame(DateReview = reviews_date11_2))
```

```{r}
#combine into one row
(dateRev11 <- rbind(df_reviewsDate11, df_reviewsDate11_2)) 
```

```{r}
#get the user ratings
reviews_rating11 <- movie11 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating11

#subset the ratings to get only 25
(sub_reviewsRating11 <- reviews_rating11[1:50])

#split the output to get on;y the rates without the \n.
(rate_split11 <- unlist(strsplit(sub_reviewsRating11, "\\s+")))

#select only the ratings to exclude the white space
(splitRate11 <- rate_split11[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating11 <- data.frame (Rating = splitRate11))
```

```{r}
#get the user ratings
reviews_rating11_2 <- movie11_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating11_2

#subset the ratings to get only 25
(sub_reviewsRating11_2 <- reviews_rating11_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split11_2 <- unlist(strsplit(sub_reviewsRating11_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate11_2 <- rate_split11_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating11_2 <- data.frame (Rating = splitRate11_2))
```

```{r}
#combine into one row
(rating11 <- rbind(df_rating11,df_rating11_2))
```

```{r}
#get the contents of the reviews
review_text11 <- movie11 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text11

#set as data frame.
(df_reviewText11 <- data.frame(TextReview = review_text11))
```

```{r}
#get the contents of the reviews
review_text11_2 <- movie11_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text11_2

#set as data frame.
(df_reviewText11_2 <- data.frame(TextReview = review_text11_2))
```

```{r}
#cobine into one row
(textRev11 <- rbind(df_reviewText11, df_reviewText11_2))
```

```{r}
#get the review title.
review_title11 <- movie11 %>%
  html_nodes("a.title") %>%
  html_text()
review_title11

#subset the review title get only 25
(sub_titrev11 <- review_title11[1:25])

(review_split11 <- unlist(strsplit(sub_titrev11, "\n")))

#set as data frame
(df_reviewTitle11 <- data.frame(TitleReview = review_split11))
```

```{r}
#get the review title.
review_title11_2 <- movie11_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title11_2

#subset the review title get only 25
(sub_titrev11_2 <- review_title11_2[1:25])

(review_split11_2 <- unlist(strsplit(sub_titrev11_2, "\n")))
#set as data frame
(df_reviewTitle11_2 <- data.frame(TitleReview = review_split11_2))
```

```{r}
(titleRev11 <- rbind(df_reviewTitle11, df_reviewTitle11_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie11 <- data.frame(Title = eleventh_title,
                        nameRev11,
                        rating11,                    
                        dateRev11,
                        textRev11,
                        titleRev11)
)
```

```{r}
library(polite)
library(rvest)

#12th movie url for the the name of the reviewer.
movie12_url <- "https://www.imdb.com/title/tt21692408/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov12 <- bow(movie12_url, user_agent = "educational purposes")

movie12 <- read_html(movie12_url)

movie12_url2 <- "https://www.imdb.com/title/tt21692408/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov12_2 <- bow(movie12_url2, user_agent = "educational purposes")

movie12_2 <- read_html(movie12_url2)
```

```{r}
#geting the 12th movie title to include it for the data frame.
(twelveth_title <- sub_movie[13])

#get the reviewer's name.
reviewer12 <- movie12 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer12

#set as data frame
(df_reviewer12 <- data.frame(Name = reviewer12))
```

```{r}
#get the reviewer's name.
reviewer12_2 <- movie12_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer12_2

#set as data frame
(df_reviewer12_2 <- data.frame(Name = reviewer12_2))
```

```{r}
#combine the output into one row
(nameRev12 <- rbind(df_reviewer12,df_reviewer12_2))
```

```{r}
#get the the date of reviews
reviews_date12 <- movie12 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate12 <- data.frame(DateReview = reviews_date12))
```

```{r}
#get the the date of reviews
reviews_date12_2 <- movie12_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate12_2 <- data.frame(DateReview = reviews_date12_2))
```

```{r}
#combine the output into one row
(dateRev12 <- rbind(df_reviewsDate12, df_reviewsDate12_2))
```

```{r}
#get the user ratings
reviews_rating12 <- movie12 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings to get only 25
(sub_reviewsRating12 <- reviews_rating12[1:50])

#split the output to get on;y the rates without the \n.
(rate_split12 <- unlist(strsplit(sub_reviewsRating12, "\\s+")))

#select only the ratings to exclude the white space
(splitRate12 <- rate_split12[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating12 <- data.frame (Rating = splitRate12))
```

```{r}
#get the user ratings
reviews_rating12_2 <- movie12_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings to get only 25
(sub_reviewsRating12_2 <- reviews_rating12_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split12_2 <- unlist(strsplit(sub_reviewsRating12_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate12_2 <- rate_split12_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating12_2 <- data.frame (Rating = splitRate12_2))
```

```{r}
#combine into one row
(rating12 <- rbind(df_rating12,df_rating12_2))
```

```{r}
#get the contents of the reviews
review_text12 <- movie12 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text12

#set as data frame.
(df_reviewText12 <- data.frame(TextReview = review_text12))
```

```{r}
#get the contents of the reviews
review_text12_2 <- movie12_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text12_2

#set as data frame.
(df_reviewText12_2 <- data.frame(TextReview = review_text12_2))
```

```{r}
#combine into one frame
(textRev12 <- rbind(df_reviewText12,df_reviewText12_2))
```

```{r}
#get the review title.
review_title12 <- movie12 %>%
  html_nodes("a.title") %>%
  html_text()
review_title12

#subset the review title get only 25
(sub_titrev12 <- review_title12[1:25])

(review_split12 <- unlist(strsplit(sub_titrev12, "\n")))

#set as data frame
(df_reviewTitle12 <- data.frame(TitleReview = review_split12))
```

```{r}
#get the review title.
review_title12_2 <- movie12_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title12_2

#subset the review title get only 25
(sub_titrev12_2 <- review_title12_2[1:25])

(review_split12_2 <- unlist(strsplit(sub_titrev12_2, "\n")))

#set as data frame
(df_reviewTitle12_2 <- data.frame(TitleReview = review_split12_2))
```

```{r}
#combine into one row
(titleRev12 <- rbind(df_reviewTitle12, df_reviewTitle12_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie12 <- data.frame(Title = twelveth_title,
                        nameRev12,
                        rating12,                    
                        dateRev12,
                        textRev12,
                        titleRev12)
)
```

```{r}
library(polite)
library(rvest)

#13th movie url for the the name of the reviewer.
movie13_url <- "https://www.imdb.com/title/tt8367814/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov13 <- bow(movie13_url, user_agent = "educational purposes")

movie13 <- read_html(movie13_url)

movie13_url2 <- "https://www.imdb.com/title/tt8367814/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov13_2 <- bow(movie13_url2, user_agent = "educational purposes")

movie13_2 <- read_html(movie13_url2)
```

```{r}
#geting the 13th movie title to include it for the data frame.
(thirteenth_title <- sub_movie[14])

#get the reviewer's name.
reviewer13 <- movie13 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer13

#set as data frame
(df_reviewer13 <- data.frame(Name = reviewer13))
```

```{r}
#get the reviewer's name.
reviewer13_2 <- movie13_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer13_2

#set as data frame
(df_reviewer13_2 <- data.frame(Name = reviewer13_2))
```

```{r}
#combine the output into one row
(nameRev13 <- rbind(df_reviewer13,df_reviewer13_2))
```

```{r}
#get the the date of reviews
reviews_date13 <- movie13 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate13 <- data.frame(DateReview = reviews_date13))
```

```{r}
#get the the date of reviews
reviews_date13_2 <- movie13_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate13_2 <- data.frame(DateReview = reviews_date13_2))
```

```{r}
#combine the output into one row
(dateRev13 <- rbind(df_reviewsDate13, df_reviewsDate13_2))
```

```{r}
#get the user ratings
reviews_rating13 <- movie13 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating13

#subset the ratings to get only 25
(sub_reviewsRating13 <- reviews_rating13[1:50])

#split the output to get on;y the rates without the \n.
(rate_split13 <- unlist(strsplit(sub_reviewsRating13, "\\s+")))

#select only the ratings to exclude the white space
(splitRate13 <- rate_split13[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating13 <- data.frame (Rating = splitRate13))
```

```{r}
#get the user ratings
reviews_rating13_2 <- movie13_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating13_2

#subset the ratings to get only 25
(sub_reviewsRating13_2 <- reviews_rating13_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split13_2 <- unlist(strsplit(sub_reviewsRating13_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate13_2 <- rate_split13_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating13_2 <- data.frame (Rating = splitRate13_2))
```

```{r}
#combine into one row
(rating13 <- rbind(df_rating13,df_rating13_2))
```

```{r}
#get the contents of the reviews
review_text13 <- movie13 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text13

#set as data frame.
(df_reviewText13 <- data.frame(TextReview = review_text13))
```

```{r}
#get the contents of the reviews
review_text13_2 <- movie13_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text13_2

#set as data frame.
(df_reviewText13_2 <- data.frame(TextReview = review_text13_2))
```

```{r}
#combine into one frame
(textRev13 <- rbind(df_reviewText13,df_reviewText13_2))
```

```{r}
#get the review title.
review_title13 <- movie13 %>%
  html_nodes("a.title") %>%
  html_text()
review_title13

#subset the review title get only 25
(sub_titrev13 <- review_title13[1:25])

(review_split13 <- unlist(strsplit(sub_titrev13, "\n")))

#set as data frame
(df_reviewTitle13 <- data.frame(TitleReview = review_split13))
```

```{r}
#get the review title.
review_title13_2 <- movie13_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title13_2

#subset the review title get only 25
(sub_titrev13_2 <- review_title13_2[1:25])

(review_split13_2 <- unlist(strsplit(sub_titrev13_2, "\n")))

#set as data frame
(df_reviewTitle13_2 <- data.frame(TitleReview = review_split13_2))
```

```{r}
#combine into one row
(titleRev13 <- rbind(df_reviewTitle13, df_reviewTitle13_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie13 <- data.frame(Title = thirteenth_title,
                        nameRev13,
                        rating13,                    
                        dateRev13,
                        textRev13,
                        titleRev13)
)
```

```{r}
library(polite)
library(rvest)

#14th movie url for the the name of the reviewer.
movie14_url <- "https://www.imdb.com/title/tt1660648/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov14 <- bow(movie14_url, user_agent = "educational purposes")

movie14 <- read_html(movie14_url)

movie14_url2 <- "https://www.imdb.com/title/tt1660648/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov14_2 <- bow(movie14_url, user_agent = "educational purposes")

movie14_2 <- read_html(movie14_url2)
```

```{r}
#geting the 14th movie title to include it for the data frame.
(fourteenth_title <- sub_movie[16])

#get the reviewer's name.
reviewer14 <- movie14 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer14

#set as data frame
(df_reviewer14 <- data.frame(Name = reviewer14))
```

```{r}
#get the reviewer's name.
reviewer14_2 <- movie14_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer14_2

#set as data frame
(df_reviewer14_2 <- data.frame(Name = reviewer14_2))
```

```{r}
#combine the output into one row
(nameRev14 <- rbind(df_reviewer14,df_reviewer14_2))
```

```{r}
#get the the date of reviews
reviews_date14 <- movie14 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate14 <- data.frame(DateReview = reviews_date14))
```

```{r}
#get the the date of reviews
reviews_date14_2 <- movie14_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate14_2 <- data.frame(DateReview = reviews_date14_2))
```

```{r}
#combine the output into one row
(dateRev14 <- rbind(df_reviewsDate14, df_reviewsDate14_2))
```

```{r}
#get the user ratings
reviews_rating14 <- movie14 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating14

#subset the ratings to get only 25
(sub_reviewsRating14 <- reviews_rating14[1:50])

#split the output to get on;y the rates without the \n.
(rate_split14 <- unlist(strsplit(sub_reviewsRating14, "\\s+")))

#select only the ratings to exclude the white space
(splitRate14 <- rate_split14[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating14 <- data.frame (Rating = splitRate4))
```

```{r}
#get the user ratings
reviews_rating14_2 <- movie14_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating14_2

#subset the ratings to get only 25
(sub_reviewsRating14_2 <- reviews_rating14_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split14_2 <- unlist(strsplit(sub_reviewsRating14_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate14_2 <- rate_split14_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating14_2 <- data.frame (Rating = splitRate14_2))
```

```{r}
#combine into one row
(rating14 <- rbind(df_rating14,df_rating14_2))
```

```{r}
#get the contents of the reviews
review_text14 <- movie14 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text14

#set as data frame.
(df_reviewText14 <- data.frame(TextReview = review_text14))
```


```{r}
#get the contents of the reviews
review_text14_2 <- movie14_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text14_2

#set as data frame.
(df_reviewText14_2 <- data.frame(TextReview = review_text14_2))
```

```{r}
#combine into one frame
(textRev14 <- rbind(df_reviewText14,df_reviewText14_2))
```

```{r}
#get the review title.
review_title14 <- movie14 %>%
  html_nodes("a.title") %>%
  html_text()
review_title14

#subset the review title get only 25
(sub_titrev14 <- review_title14[1:25])

(review_split14 <- unlist(strsplit(sub_titrev14, "\n")))

#set as data frame
(df_reviewTitle14 <- data.frame(TitleReview = review_split14))
```

```{r}
#get the review title.
review_title14_2 <- movie14_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title14_2

#subset the review title get only 25
(sub_titrev14_2 <- review_title14_2[1:25])

(review_split14_2 <- unlist(strsplit(sub_titrev14_2, "\n")))

#set as data frame
(df_reviewTitle14_2 <- data.frame(TitleReview = review_split14_2))
```

```{r}
#combine into one row
(titleRev14 <- rbind(df_reviewTitle14, df_reviewTitle14_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie14 <- data.frame(Title = fourteenth_title,
                        nameRev14,
                        rating14,                    
                        dateRev14,
                        textRev14,
                        titleRev14)
)
```

```{r}
moviesRev11234 <- rbind(df_movie11, df_movie12, df_movie13, df_movie14)
moviesRev11234
```


```{r}
write.csv(moviesRev11234, "IMDBmoviesReviews(4th_200).csv")

read.csv("IMDBmoviesReviews(4th_200).csv")
```

```{r}
library(polite)
library(rvest)

#15th movie url for the the name of the reviewer.
movie15_url <- "https://www.imdb.com/title/tt4513678/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov15 <- bow(movie15_url, user_agent = "educational purposes")

movie15 <- read_html(movie15_url)

movie15_url2 <- "https://www.imdb.com/title/tt4513678/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov15_2 <- bow(movie15_url2, user_agent = "educational purposes")

movie15_2 <- read_html(movie15_url2)
```

```{r}
#geting the 15th movie title to include it for the data frame.
(fifteenth_title <- sub_movie[17])

#get the reviewer's name.
reviewer15 <- movie15 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer15

#set as data frame
(df_reviewer15 <- data.frame(Name = reviewer15))
```

```{r}
#get the reviewer's name.
reviewer15_2 <- movie15_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer15_2

#set as data frame
(df_reviewer15_2 <- data.frame(Name = reviewer15_2))
```

```{r}
#combine into one row
(nameRev15 <- rbind(df_reviewer15, df_reviewer15_2)) 
```

```{r}
#get the the date of reviews
reviews_date15 <- movie15 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate15 <- data.frame(DateReview = reviews_date15))
```

```{r}
#get the the date of reviews
reviews_date15_2 <- movie15_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate15_2 <- data.frame(DateReview = reviews_date15_2))
```

```{r}
#combine into one row
(dateRev15 <- rbind(df_reviewsDate15, df_reviewsDate15_2)) 
```

```{r}
#get the user ratings
reviews_rating15 <- movie15 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating15

#subset the ratings 
(sub_reviewsRating15 <- reviews_rating15[1:50])

#split the output to get on;y the rates without the \n.
(rate_split15 <- unlist(strsplit(sub_reviewsRating15, "\\s+")))

#select only the ratings to exclude the white space
(splitRate15 <- rate_split15[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating15 <- data.frame (Rating = splitRate15))
```

```{r}
#get the user ratings
reviews_rating15_2 <- movie15_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating15_2

#subset the ratings 
(sub_reviewsRating15_2 <- reviews_rating15_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split15_2 <- unlist(strsplit(sub_reviewsRating15_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate15_2 <- rate_split15_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating15_2 <- data.frame (Rating = splitRate15_2))
```

```{r}
#combine into one row
(rating15 <- rbind(df_rating15,df_rating15_2))
```

```{r}
#get the contents of the reviews
review_text15 <- movie15 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text15

#set as data frame.
(df_reviewText15 <- data.frame(TextReview = review_text15))
```

```{r}
#get the contents of the reviews
review_text15_2 <- movie15_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text15_2

#set as data frame.
(df_reviewText15_2 <- data.frame(TextReview = review_text15_2))
```

```{r}
#cobine into one row
(textRev15 <- rbind(df_reviewText15, df_reviewText15_2))
```

```{r}
#get the review title.
review_title15 <- movie15 %>%
  html_nodes("a.title") %>%
  html_text()
review_title15

#subset the review title get only 25
(sub_titrev15 <- review_title15[1:25])

(review_split15 <- unlist(strsplit(sub_titrev15, "\n")))

#set as data frame
(df_reviewTitle15 <- data.frame(TitleReview = review_split15))
```

```{r}
#get the review title.
review_title15_2 <- movie15_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title15_2

#subset the review title get only 25
(sub_titrev15_2 <- review_title15_2[1:25])

(review_split15_2 <- unlist(strsplit(sub_titrev15_2, "\n")))
#set as data frame
(df_reviewTitle15_2 <- data.frame(TitleReview = review_split15_2))
```

```{r}
(titleRev15 <- rbind(df_reviewTitle15, df_reviewTitle15_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie15 <- data.frame(Title = fifteenth_title,
                        nameRev15,
                        rating15,                    
                        dateRev15,
                        textRev15,
                        titleRev15)
)
```

```{r}
library(polite)
library(rvest)

#16th movie url for the the name of the reviewer.
movie16_url <- "https://www.imdb.com/title/tt17009710/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov16 <- bow(movie16_url, user_agent = "educational purposes")

movie16 <- read_html(movie16_url)

movie16_url2 <- "https://www.imdb.com/title/tt17009710/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov16_2 <- bow(movie16_url2, user_agent = "educational purposes")

movie16_2 <- read_html(movie16_url2)
```

```{r}
#geting the 16th movie title to include it for the data frame.
(sixteenth_title <- sub_movie[19])

#get the reviewer's name.
reviewer16 <- movie16 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer16

#set as data frame
(df_reviewer16 <- data.frame(Name = reviewer16))
```

```{r}
#get the reviewer's name.
reviewer16_2 <- movie16_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer16_2

#set as data frame
(df_reviewer16_2 <- data.frame(Name = reviewer16_2))
```

```{r}
#combine the output into one row
(nameRev16 <- rbind(df_reviewer16,df_reviewer16_2))
```

```{r}
#get the the date of reviews
reviews_date16 <- movie16 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate16 <- data.frame(DateReview = reviews_date16))
```

```{r}
#get the the date of reviews
reviews_date16_2 <- movie16_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate16_2 <- data.frame(DateReview = reviews_date16_2))
```

```{r}
#combine the output into one row
(dateRev16 <- rbind(df_reviewsDate16, df_reviewsDate16_2))
```

```{r}
#get the user ratings
reviews_rating16 <- movie16 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings 
(sub_reviewsRating16 <- reviews_rating16[1:50])

#split the output to get on;y the rates without the \n.
(rate_split16 <- unlist(strsplit(sub_reviewsRating16, "\\s+")))

#select only the ratings to exclude the white space
(splitRate16 <- rate_split16[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating16 <- data.frame (Rating = splitRate16))
```

```{r}
#get the user ratings
reviews_rating16_2 <- movie16_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings
(sub_reviewsRating16_2 <- reviews_rating16_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split16_2 <- unlist(strsplit(sub_reviewsRating16_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate16_2 <- rate_split16_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating16_2 <- data.frame (Rating = splitRate16_2))
```

```{r}
#combine into one row
(rating16 <- rbind(df_rating16,df_rating16_2))
```

```{r}
#get the contents of the reviews
review_text16 <- movie16 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text16

#set as data frame.
(df_reviewText16 <- data.frame(TextReview = review_text16))
```

```{r}
#get the contents of the reviews
review_text16_2 <- movie16_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text16_2

#set as data frame.
(df_reviewText16_2 <- data.frame(TextReview = review_text16_2))
```

```{r}
#combine into one frame
(textRev16 <- rbind(df_reviewText16,df_reviewText16_2))
```

```{r}
#get the review title.
review_title16 <- movie16 %>%
  html_nodes("a.title") %>%
  html_text()
review_title16

#subset the review title get only 25
(sub_titrev16 <- review_title16[1:25])

(review_split16 <- unlist(strsplit(sub_titrev16, "\n")))

#set as data frame
(df_reviewTitle16 <- data.frame(TitleReview = review_split16))
```

```{r}
#get the review title.
review_title16_2 <- movie16_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title16_2

#subset the review title get only 25
(sub_titrev16_2 <- review_title16_2[1:25])

(review_split16_2 <- unlist(strsplit(sub_titrev16_2, "\n")))

#set as data frame
(df_reviewTitle16_2 <- data.frame(TitleReview = review_split16_2))
```

```{r}
#combine into one row
(titleRev16 <- rbind(df_reviewTitle16, df_reviewTitle16_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie16 <- data.frame(Title = sixteenth_title,
                        nameRev16,
                        rating16,                    
                        dateRev16,
                        textRev16,
                        titleRev16)
)
```

```{r}
library(polite)
library(rvest)

#17th movie url for the the name of the reviewer.
movie17_url <- "https://www.imdb.com/title/tt19637052/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov17 <- bow(movie17_url, user_agent = "educational purposes")

movie17 <- read_html(movie17_url)

movie17_url2 <- "https://www.imdb.com/title/tt19637052/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov17_2 <- bow(movie17_url2, user_agent = "educational purposes")

movie17_2 <- read_html(movie17_url2)
```

```{r}
#geting the 17th movie title to include it for the data frame.
(seventeenth_title <- sub_movie[20])

#get the reviewer's name.
reviewer17 <- movie17 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer17

#set as data frame
(df_reviewer17 <- data.frame(Name = reviewer17))
```

```{r}
#get the reviewer's name.
reviewer17_2 <- movie17_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer17_2

#set as data frame
(df_reviewer17_2 <- data.frame(Name = reviewer17_2))
```

```{r}
#combine the output into one row
(nameRev17 <- rbind(df_reviewer17,df_reviewer17_2))
```

```{r}
#get the the date of reviews
reviews_date17 <- movie17 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate17 <- data.frame(DateReview = reviews_date17))
```

```{r}
#get the the date of reviews
reviews_date17_2 <- movie17_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate17_2 <- data.frame(DateReview = reviews_date17_2))

#combine the output into one row
(dateRev17 <- rbind(df_reviewsDate17, df_reviewsDate17_2))
```

```{r}
#get the user ratings
reviews_rating17 <- movie17 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating17

#subset the ratings
(sub_reviewsRating17 <- reviews_rating17[1:50])

#split the output to get on;y the rates without the \n.
(rate_split17 <- unlist(strsplit(sub_reviewsRating17, "\\s+")))

#select only the ratings to exclude the white space
(splitRate17 <- rate_split17[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating17 <- data.frame (Rating = splitRate17))
```

```{r}
#get the user ratings
reviews_rating17_2 <- movie17_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating17_2

#subset the ratings 
(sub_reviewsRating17_2 <- reviews_rating17_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split17_2 <- unlist(strsplit(sub_reviewsRating17_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate17_2 <- rate_split17_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating17_2 <- data.frame (Rating = splitRate17_2))
```

```{r}
#combine into one row
(rating17 <- rbind(df_rating17,df_rating17_2))
```

```{r}
#get the contents of the reviews
review_text17 <- movie17 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text17

#set as data frame.
(df_reviewText17 <- data.frame(TextReview = review_text17))
```

```{r}
#get the contents of the reviews
review_text17_2 <- movie17_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text17_2

#set as data frame.
(df_reviewText17_2 <- data.frame(TextReview = review_text17_2))
```

```{r}
#combine into one frame
(textRev17 <- rbind(df_reviewText17,df_reviewText17_2))
```

```{r}
#get the review title.
review_title17 <- movie17 %>%
  html_nodes("a.title") %>%
  html_text()
review_title17

#subset the review title get only 25
(sub_titrev17 <- review_title17[1:25])

(review_split17 <- unlist(strsplit(sub_titrev17, "\n")))

#set as data frame
(df_reviewTitle17 <- data.frame(TitleReview = review_split17))
```

```{r}
#get the review title.
review_title17_2 <- movie17_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title17_2

#subset the review title get only 25
(sub_titrev17_2 <- review_title17_2[1:25])

(review_split17_2 <- unlist(strsplit(sub_titrev17_2, "\n")))

#set as data frame
(df_reviewTitle17_2 <- data.frame(TitleReview = review_split17_2))
```

```{r}
#combine into one row
(titleRev17 <- rbind(df_reviewTitle17, df_reviewTitle17_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie17 <- data.frame(Title = seventeenth_title,
                        nameRev17,
                        rating17,                    
                        dateRev17,
                        textRev17,
                        titleRev17)
)
```

```{r}
library(polite)
library(rvest)

#18th movie url for the the name of the reviewer.
movie18_url <- "https://www.imdb.com/title/tt6166392/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov18 <- bow(movie18_url, user_agent = "educational purposes")

movie18 <- read_html(movie18_url)

movie18_url2 <- "https://www.imdb.com/title/tt6166392/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov18_2 <- bow(movie18_url, user_agent = "educational purposes")

movie18_2 <- read_html(movie18_url2)
```

```{r}
#geting the 18th movie title to include it for the data frame.
(eighteenth_title <- sub_movie[21])

#get the reviewer's name.
reviewer18 <- movie18 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer18

#set as data frame
(df_reviewer18 <- data.frame(Name = reviewer18))
```

```{r}
#get the reviewer's name.
reviewer18_2 <- movie18_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer18_2

#set as data frame
(df_reviewer18_2 <- data.frame(Name = reviewer18_2))
```

```{r}
#combine the output into one row
(nameRev18 <- rbind(df_reviewer18,df_reviewer18_2))
```

```{r}
#get the the date of reviews
reviews_date18 <- movie18 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate18 <- data.frame(DateReview = reviews_date18))
```

```{r}
#get the the date of reviews
reviews_date18_2 <- movie18_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate18_2 <- data.frame(DateReview = reviews_date18_2))
```

```{r}
#combine the output into one row
(dateRev18 <- rbind(df_reviewsDate18, df_reviewsDate18_2))
```

```{r}
#get the user ratings
reviews_rating18 <- movie18 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating18

#subset the ratings 
(sub_reviewsRating18 <- reviews_rating18[1:50])

#split the output to get only the rates without the \n.
(rate_split18 <- unlist(strsplit(sub_reviewsRating18, "\\s+")))

#select only the ratings to exclude the white space
(splitRate18 <- rate_split18[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating18 <- data.frame (Rating = splitRate18))
```

```{r}
#get the user ratings
reviews_rating18_2 <- movie18_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating18_2

#subset the ratings
(sub_reviewsRating18_2 <- reviews_rating18_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split18_2 <- unlist(strsplit(sub_reviewsRating18_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate18_2 <- rate_split18_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating18_2 <- data.frame (Rating = splitRate18_2))
```

```{r}
#combine into one row
(rating18 <- rbind(df_rating18,df_rating18_2))
```

```{r}
#get the contents of the reviews
review_text18 <- movie18 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text18

#set as data frame.
(df_reviewText18 <- data.frame(TextReview = review_text18))
```


```{r}
#get the contents of the reviews
review_text18_2 <- movie18_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text18_2

#set as data frame.
(df_reviewText18_2 <- data.frame(TextReview = review_text18_2))
```

```{r}
#combine into one frame
(textRev18 <- rbind(df_reviewText18,df_reviewText18_2))
```

```{r}
#get the review title.
review_title18 <- movie18 %>%
  html_nodes("a.title") %>%
  html_text()
review_title18

#subset the review title get only 25
(sub_titrev18 <- review_title18[1:25])

(review_split18 <- unlist(strsplit(sub_titrev18, "\n")))

#set as data frame
(df_reviewTitle18 <- data.frame(TitleReview = review_split18))
```

```{r}
#get the review title.
review_title18_2 <- movie18_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title18_2

#subset the review title get only 25
(sub_titrev18_2 <- review_title18_2[1:25])

(review_split18_2 <- unlist(strsplit(sub_titrev18_2, "\n")))

#set as data frame
(df_reviewTitle18_2 <- data.frame(TitleReview = review_split18_2))
```

```{r}
#combine into one row
(titleRev18 <- rbind(df_reviewTitle18, df_reviewTitle18_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie18 <- data.frame(Title = eighteenth_title,
                        nameRev18,
                        rating18,                    
                        dateRev18,
                        textRev18,
                        titleRev18)
)
```

```{r}
moviesRev15678 <- rbind(df_movie15, df_movie16, df_movie17, df_movie18)
moviesRev15678
```


```{r}
write.csv(moviesRev15678, "IMDBmoviesReviews(5th_200).csv")

read.csv("IMDBmoviesReviews(5th_200).csv")
```

```{r}
library(polite)
library(rvest)

#19th movie url for the the name of the reviewer.
movie19_url <- "https://www.imdb.com/title/tt26047818/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov19 <- bow(movie19_url, user_agent = "educational purposes")

movie19 <- read_html(movie19_url)

movie19_url2 <- "https://www.imdb.com/title/tt26047818/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov19_2 <- bow(movie19_url2, user_agent = "educational purposes")

movie19_2 <- read_html(movie19_url2)
```

```{r}
#geting the 19th movie title to include it for the data frame.
(nineteenth_title <- sub_movie[23])

#get the reviewer's name.
reviewer19 <- movie19 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer19

#set as data frame
(df_reviewer19 <- data.frame(Name = reviewer19))
```

```{r}
#get the reviewer's name.
reviewer19_2 <- movie19_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer19_2

#set as data frame
(df_reviewer19_2 <- data.frame(Name = reviewer19_2))
```

```{r}
#combine into one row
(nameRev19 <- rbind(df_reviewer19, df_reviewer19_2)) 
```

```{r}
#get the the date of reviews
reviews_date19 <- movie19 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate19 <- data.frame(DateReview = reviews_date19))
```

```{r}
#get the the date of reviews
reviews_date19_2 <- movie19_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate19_2 <- data.frame(DateReview = reviews_date19_2))
```

```{r}
#combine into one row
(dateRev19 <- rbind(df_reviewsDate19, df_reviewsDate19_2)) 
```

```{r}
#get the user ratings
reviews_rating19 <- movie19 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating19

#subset the ratings 
(sub_reviewsRating19 <- reviews_rating19[1:50])

#split the output to get on;y the rates without the \n.
(rate_split19 <- unlist(strsplit(sub_reviewsRating19, "\\s+")))

#select only the ratings to exclude the white space
(splitRate19 <- rate_split19[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating19 <- data.frame (Rating = splitRate19))
```

```{r}
#get the user ratings
reviews_rating19_2 <- movie19_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating19_2

#subset the ratings 
(sub_reviewsRating19_2 <- reviews_rating19_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split19_2 <- unlist(strsplit(sub_reviewsRating19_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate19_2 <- rate_split19_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating19_2 <- data.frame (Rating = splitRate19_2))
```

```{r}
#combine into one row
(rating19 <- rbind(df_rating19,df_rating19_2))
```

```{r}
#get the contents of the reviews
review_text19 <- movie19 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text19

#set as data frame.
(df_reviewText19 <- data.frame(TextReview = review_text19))
```

```{r}
#get the contents of the reviews
review_text19_2 <- movie19_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text19_2

#set as data frame.
(df_reviewText19_2 <- data.frame(TextReview = review_text19_2))
```

```{r}
#cobine into one row
(textRev19 <- rbind(df_reviewText19, df_reviewText19_2))
```

```{r}
#get the review title.
review_title19 <- movie19 %>%
  html_nodes("a.title") %>%
  html_text()
review_title19

#subset the review title get only 25
(sub_titrev19 <- review_title19[1:25])

(review_split19 <- unlist(strsplit(sub_titrev19, "\n")))

#set as data frame
(df_reviewTitle19 <- data.frame(TitleReview = review_split19))
```

```{r}
#get the review title.
review_title19_2 <- movie19_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title19_2

#subset the review title get only 25
(sub_titrev19_2 <- review_title19_2[1:25])

(review_split19_2 <- unlist(strsplit(sub_titrev19_2, "\n")))
#set as data frame
(df_reviewTitle19_2 <- data.frame(TitleReview = review_split19_2))
```

```{r}
(titleRev19 <- rbind(df_reviewTitle19, df_reviewTitle19_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie19 <- data.frame(Title = nineteenth_title,
                        nameRev19,
                        rating19,                    
                        dateRev19,
                        textRev19,
                        titleRev19)
)
```

```{r}
library(polite)
library(rvest)

#20th movie url for the the name of the reviewer.
movie20_url <- "https://www.imdb.com/title/tt0094721/reviews?sort=curated&dir=desc&ratingFilter=9"
session_Mov20 <- bow(movie20_url, user_agent = "educational purposes")

movie20 <- read_html(movie20_url)

movie20_url2 <- "https://www.imdb.com/title/tt0094721/reviews?sort=curated&dir=desc&ratingFilter=8"
session_Mov20_2 <- bow(movie20_url2, user_agent = "educational purposes")

movie20_2 <- read_html(movie20_url2)
```

```{r}
#geting the 20th movie title to include it for the data frame.
(twentieth_title <- sub_movie[24])

#get the reviewer's name.
reviewer20 <- movie20 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer20

#set as data frame
(df_reviewer20 <- data.frame(Name = reviewer20))
```

```{r}
#get the reviewer's name.
(reviewer20_2 <- movie20_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer20_2 <- data.frame(Name = reviewer20_2))
```

```{r}
#combine the output into one row
(nameRev20 <- rbind(df_reviewer20,df_reviewer20_2))
```

```{r}
#get the the date of reviews
reviews_date20 <- movie20 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate20 <- data.frame(DateReview = reviews_date20))
```

```{r}
#get the the date of reviews
reviews_date20_2 <- movie20_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate20_2 <- data.frame(DateReview = reviews_date20_2))
```

```{r}
#combine the output into one row
(dateRev20 <- rbind(df_reviewsDate20, df_reviewsDate20_2))
```

```{r}
#get the user ratings
reviews_rating20 <- movie20 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings 
(sub_reviewsRating20 <- reviews_rating20[1:50])

#split the output to get on;y the rates without the \n.
(rate_split20 <- unlist(strsplit(sub_reviewsRating20, "\\s+")))

#select only the ratings to exclude the white space
(splitRate20 <- rate_split20[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating20 <- data.frame (Rating = splitRate20))
```

```{r}
#get the user ratings
reviews_rating20_2 <- movie20_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings
(sub_reviewsRating20_2 <- reviews_rating20_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split20_2 <- unlist(strsplit(sub_reviewsRating20_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate20_2 <- rate_split20_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating20_2 <- data.frame (Rating = splitRate20_2))
```

```{r}
#combine into one row
(rating20 <- rbind(df_rating20,df_rating20_2))
```

```{r}
#get the contents of the reviews
review_text20 <- movie20 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text20

#set as data frame.
(df_reviewText20 <- data.frame(TextReview = review_text20))
```

```{r}
#get the contents of the reviews
review_text20_2 <- movie20_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text20_2

#set as data frame.
(df_reviewText20_2 <- data.frame(TextReview = review_text20_2))
```

```{r}
#combine into one frame
(textRev20 <- rbind(df_reviewText20,df_reviewText20_2))
```

```{r}
#get the review title.
review_title20 <- movie20 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev20 <- review_title20[1:25])

(review_split20 <- unlist(strsplit(sub_titrev20, "\n")))

#set as data frame
(df_reviewTitle20 <- data.frame(TitleReview = review_split20))
```

```{r}
#get the review title.
review_title20_2 <- movie20_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title20_2

#subset the review title get only 25
(sub_titrev20_2 <- review_title20_2[1:25])

(review_split20_2 <- unlist(strsplit(sub_titrev20_2, "\n")))

#set as data frame
(df_reviewTitle20_2 <- data.frame(TitleReview = review_split20_2))
```

```{r}
#combine into one row
(titleRev20 <- rbind(df_reviewTitle20, df_reviewTitle20_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie20 <- data.frame(Title = twentieth_title,
                        nameRev20,
                        rating20,                    
                        dateRev20,
                        textRev20,
                        titleRev20)
)
```

```{r}
library(polite)
library(rvest)

#21 movie url for the the name of the reviewer.
movie21_url <- "https://www.imdb.com/title/tt11057302/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov21 <- bow(movie21_url, user_agent = "educational purposes")

movie21 <- read_html(movie21_url)

movie21_url2 <- "https://www.imdb.com/title/tt11057302/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov21_2 <- bow(movie21_url2, user_agent = "educational purposes")

movie21_2 <- read_html(movie21_url2)
```

```{r}
#geting the 21th movie title to include it for the data frame.
(twentyone_title <- sub_movie[25])

#get the reviewer's name.
(reviewer21 <- movie21 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer21 <- data.frame(Name = reviewer21))
```

```{r}
#get the reviewer's name.
(reviewer21_2 <- movie21_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer21_2 <- data.frame(Name = reviewer21_2))
```

```{r}
#combine the output into one row
(nameRev21 <- rbind(df_reviewer21,df_reviewer21_2))
```

```{r}
#get the the date of reviews
reviews_date21 <- movie21 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate21 <- data.frame(DateReview = reviews_date21))
```

```{r}
#get the the date of reviews
reviews_date21_2 <- movie21_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate21_2 <- data.frame(DateReview = reviews_date21_2))

#combine the output into one row
(dateRev21 <- rbind(df_reviewsDate21, df_reviewsDate21_2))
```

```{r}
#get the user ratings
(reviews_rating21 <- movie21 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings
(sub_reviewsRating21 <- reviews_rating21[1:50])

#split the output to get on;y the rates without the \n.
(rate_split21 <- unlist(strsplit(sub_reviewsRating21, "\\s+")))

#select only the ratings to exclude the white space
(splitRate21 <- rate_split21[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating21 <- data.frame (Rating = splitRate21))
```

```{r}
#get the user ratings
(reviews_rating21_2 <- movie21_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings 
(sub_reviewsRating21_2 <- reviews_rating21_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split21_2 <- unlist(strsplit(sub_reviewsRating21_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate21_2 <- rate_split21_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating21_2 <- data.frame (Rating = splitRate21_2))
```

```{r}
#combine into one row
(rating21 <- rbind(df_rating21,df_rating21_2))
```

```{r}
#get the contents of the reviews
(review_text21 <- movie21 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText21 <- data.frame(TextReview = review_text21))
```

```{r}
#get the contents of the reviews
review_text21_2 <- movie21_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText21_2 <- data.frame(TextReview = review_text21_2))
```

```{r}
#combine into one frame
(textRev21 <- rbind(df_reviewText21,df_reviewText21_2))
```

```{r}
#get the review title.
review_title21 <- movie21 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev21 <- review_title21[1:25])

(review_split21 <- unlist(strsplit(sub_titrev21, "\n")))

#set as data frame
(df_reviewTitle21 <- data.frame(TitleReview = review_split21))
```

```{r}
#get the review title.
review_title21_2 <- movie21_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev21_2 <- review_title21_2[1:25])

(review_split21_2 <- unlist(strsplit(sub_titrev21_2, "\n")))

#set as data frame
(df_reviewTitle21_2 <- data.frame(TitleReview = review_split21_2))
```

```{r}
#combine into one row
(titleRev21 <- rbind(df_reviewTitle21, df_reviewTitle21_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie21 <- data.frame(Title = twentyone_title,
                        nameRev21,
                        rating21,                    
                        dateRev21,
                        textRev21,
                        titleRev21)
)
```

```{r}
library(polite)
library(rvest)

#22 movie url for the the name of the reviewer.
movie22_url <- "https://www.imdb.com/title/tt0087332/reviews?sort=curated&dir=desc&ratingFilter=7"
session_Mov22 <- bow(movie22_url, user_agent = "educational purposes")

movie22 <- read_html(movie22_url)

movie22_url2 <- "https://www.imdb.com/title/tt0087332/reviews?sort=curated&dir=desc&ratingFilter=10"
session_Mov22_2 <- bow(movie22_url, user_agent = "educational purposes")

movie22_2 <- read_html(movie22_url2)
```

```{r}
#geting the 22th movie title to include it for the data frame.
(twentytwo_title <- sub_movie[27])

#get the reviewer's name.
(reviewer22 <- movie22 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer22 <- data.frame(Name = reviewer22))
```

```{r}
#get the reviewer's name.
(reviewer22_2 <- movie22_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer22_2 <- data.frame(Name = reviewer22_2))
```

```{r}
#combine the output into one row
(nameRev22 <- rbind(df_reviewer22,df_reviewer22_2))
```

```{r}
#get the the date of reviews
reviews_date22 <- movie22 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate22 <- data.frame(DateReview = reviews_date22))
```

```{r}
#get the the date of reviews
reviews_date22_2 <- movie22_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate22_2 <- data.frame(DateReview = reviews_date22_2))
```

```{r}
#combine the output into one row
(dateRev22 <- rbind(df_reviewsDate22, df_reviewsDate22_2))
```

```{r}
#get the user ratings
reviews_rating22 <- movie22 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating22

#subset the ratings 
(sub_reviewsRating22 <- reviews_rating22[1:50])

#split the output to get only the rates without the \n.
(rate_split22 <- unlist(strsplit(sub_reviewsRating22, "\\s+")))

#select only the ratings to exclude the white space
(splitRate22 <- rate_split22[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating22 <- data.frame (Rating = splitRate22))
```

```{r}
#get the user ratings
reviews_rating22_2 <- movie22_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating22_2

#subset the ratings
(sub_reviewsRating22_2 <- reviews_rating22_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split22_2 <- unlist(strsplit(sub_reviewsRating22_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate22_2 <- rate_split22_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating22_2 <- data.frame (Rating = splitRate22_2))
```

```{r}
#combine into one row
(rating22 <- rbind(df_rating22,df_rating22_2))
```

```{r}
#get the contents of the reviews
review_text22 <- movie22 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText22 <- data.frame(TextReview = review_text22))
```


```{r}
#get the contents of the reviews
review_text22_2 <- movie22_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText22_2 <- data.frame(TextReview = review_text22_2))
```

```{r}
#combine into one frame
(textRev22 <- rbind(df_reviewText22,df_reviewText22_2))
```

```{r}
#get the review title.
review_title22 <- movie22 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev22 <- review_title22[1:25])

(review_split22 <- unlist(strsplit(sub_titrev22, "\n")))

#set as data frame
(df_reviewTitle22 <- data.frame(TitleReview = review_split22))
```

```{r}
#get the review title.
review_title22_2 <- movie22_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev22_2 <- review_title22_2[1:25])

(review_split22_2 <- unlist(strsplit(sub_titrev22_2, "\n")))

#set as data frame
(df_reviewTitle22_2 <- data.frame(TitleReview = review_split22_2))
```

```{r}
#combine into one row
(titleRev22 <- rbind(df_reviewTitle22, df_reviewTitle22_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie22 <- data.frame(Title = twentytwo_title,
                        nameRev22,
                        rating22,                    
                        dateRev22,
                        textRev22,
                        titleRev22)
)
```

```{r}
(moviesRev1920122 <- rbind(df_movie19, df_movie20, df_movie21, df_movie22))
```


```{r}
write.csv(moviesRev1920122, "IMDBmoviesReviews(6th_200).csv")

read.csv("IMDBmoviesReviews(6th_200).csv")
```

```{r}
library(polite)
library(rvest)

#23th movie url for the the name of the reviewer.
movie23_url <- "https://www.imdb.com/title/tt7160372/reviews?sort=curated&dir=desc&ratingFilter=8"
session_Mov23 <- bow(movie23_url, user_agent = "educational purposes")

movie23 <- read_html(movie23_url)

movie23_url2 <- "https://www.imdb.com/title/tt7160372/reviews?sort=curated&dir=desc&ratingFilter=5"
session_Mov23_2 <- bow(movie23_url2, user_agent = "educational purposes")

movie23_2 <- read_html(movie23_url2)
```

```{r}
#geting the 23rd movie title to include it for the data frame.
(twentythree_title <- sub_movie[30])

#get the reviewer's name.
(reviewer23 <- movie23 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer23 <- data.frame(Name = reviewer23))
```

```{r}
#get the reviewer's name.
(reviewer23_2 <- movie23_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer23_2 <- data.frame(Name = reviewer23_2))
```

```{r}
#combine into one row
(nameRev23 <- rbind(df_reviewer23, df_reviewer23_2)) 
```

```{r}
#get the the date of reviews
reviews_date23 <- movie23 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate23 <- data.frame(DateReview = reviews_date23))
```

```{r}
#get the the date of reviews
reviews_date23_2 <- movie23_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate23_2 <- data.frame(DateReview = reviews_date23_2))
```

```{r}
#combine into one row
(dateRev23 <- rbind(df_reviewsDate23, df_reviewsDate23_2)) 
```

```{r}
#get the user ratings
(reviews_rating23 <- movie23 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings 
(sub_reviewsRating23 <- reviews_rating23[1:50])

#split the output to get on;y the rates without the \n.
(rate_split23 <- unlist(strsplit(sub_reviewsRating23, "\\s+")))

#select only the ratings to exclude the white space
(splitRate23 <- rate_split23[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating23 <- data.frame (Rating = splitRate23))
```

```{r}
#get the user ratings
(reviews_rating23_2 <- movie23_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings 
(sub_reviewsRating23_2 <- reviews_rating23_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split23_2 <- unlist(strsplit(sub_reviewsRating23_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate23_2 <- rate_split23_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating23_2 <- data.frame (Rating = splitRate23_2))
```

```{r}
#combine into one row
(rating23 <- rbind(df_rating23,df_rating23_2))
```

```{r}
#get the contents of the reviews
(review_text23 <- movie23 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText23 <- data.frame(TextReview = review_text23))
```

```{r}
#get the contents of the reviews
(review_text23_2 <- movie23_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText23_2 <- data.frame(TextReview = review_text23_2))
```

```{r}
#cobine into one row
(textRev23 <- rbind(df_reviewText23, df_reviewText23_2))
```

```{r}
#get the review title.
review_title23 <- movie23 %>%
  html_nodes("a.title") %>%
  html_text()
review_title23

#subset the review title get only 25
(sub_titrev23 <- review_title23[1:25])

(review_split23 <- unlist(strsplit(sub_titrev23, "\n")))

#set as data frame
(df_reviewTitle23 <- data.frame(TitleReview = review_split23))
```

```{r}
#get the review title.
review_title23_2 <- movie23_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev23_2 <- review_title23_2[1:25])

(review_split23_2 <- unlist(strsplit(sub_titrev23_2, "\n")))
#set as data frame
(df_reviewTitle23_2 <- data.frame(TitleReview = review_split23_2))
```

```{r}
(titleRev23 <- rbind(df_reviewTitle23, df_reviewTitle23_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie23 <- data.frame(Title = twentythree_title,
                        nameRev23,
                        rating23,                    
                        dateRev23,
                        textRev23,
                        titleRev23)
)
```

```{r}
library(polite)
library(rvest)

#24th movie url for the the name of the reviewer.
movie24_url <- "https://www.imdb.com/title/tt13818368/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov24 <- bow(movie24_url, user_agent = "educational purposes")

movie24 <- read_html(movie24_url)

movie24_url2 <- "https://www.imdb.com/title/tt13818368/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov24_2 <- bow(movie24_url2, user_agent = "educational purposes")

movie24_2 <- read_html(movie24_url2)
```

```{r}
#geting the 24th movie title to include it for the data frame.
(twentyfour_title <- sub_movie[32])

#get the reviewer's name.
(reviewer24 <- movie24 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer24 <- data.frame(Name = reviewer24))
```

```{r}
#get the reviewer's name.
(reviewer24_2 <- movie24_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer24_2 <- data.frame(Name = reviewer24_2))
```

```{r}
#combine the output into one row
(nameRev24 <- rbind(df_reviewer20,df_reviewer20_2))
```

```{r}
#get the the date of reviews
reviews_date24 <- movie24 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate24 <- data.frame(DateReview = reviews_date24))
```

```{r}
#get the the date of reviews
reviews_date24_2 <- movie24_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate24_2 <- data.frame(DateReview = reviews_date24_2))
```

```{r}
#combine the output into one row
(dateRev24 <- rbind(df_reviewsDate24, df_reviewsDate24_2))
```

```{r}
#get the user ratings
reviews_rating24 <- movie24 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings 
(sub_reviewsRating24 <- reviews_rating24[1:50])

#split the output to get on;y the rates without the \n.
(rate_split24 <- unlist(strsplit(sub_reviewsRating24, "\\s+")))

#select only the ratings to exclude the white space
(splitRate24 <- rate_split24[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating24 <- data.frame (Rating = splitRate24))
```

```{r}
#get the user ratings
reviews_rating24_2 <- movie24_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings
(sub_reviewsRating24_2 <- reviews_rating24_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split24_2 <- unlist(strsplit(sub_reviewsRating24_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate24_2 <- rate_split24_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating24_2 <- data.frame (Rating = splitRate24_2))
```

```{r}
#combine into one row
(rating24 <- rbind(df_rating24,df_rating24_2))
```

```{r}
#get the contents of the reviews
review_text24 <- movie24 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText24 <- data.frame(TextReview = review_text24))
```

```{r}
#get the contents of the reviews
review_text24_2 <- movie24_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText24_2 <- data.frame(TextReview = review_text24_2))
```

```{r}
#combine into one frame
(textRev24 <- rbind(df_reviewText24,df_reviewText24_2))
```

```{r}
#get the review title.
review_title24 <- movie24 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev24 <- review_title24[1:25])

(review_split24 <- unlist(strsplit(sub_titrev24, "\n")))

#set as data frame
(df_reviewTitle24 <- data.frame(TitleReview = review_split24))
```

```{r}
#get the review title.
review_title24_2 <- movie24_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev24_2 <- review_title24_2[1:25])

(review_split24_2 <- unlist(strsplit(sub_titrev24_2, "\n")))

#set as data frame
(df_reviewTitle24_2 <- data.frame(TitleReview = review_split24_2))
```

```{r}
#combine into one row
(titleRev24 <- rbind(df_reviewTitle24, df_reviewTitle24_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie24 <- data.frame(Title = twentyfour_title,
                        nameRev24,
                        rating24,                    
                        dateRev24,
                        textRev24,
                        titleRev24)
)
```

```{r}
library(polite)
library(rvest)

#25 movie url for the the name of the reviewer.
movie25_url <- "https://www.imdb.com/title/tt21957774/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov25 <- bow(movie25_url, user_agent = "educational purposes")

movie25 <- read_html(movie25_url)

movie25_url2 <- "https://www.imdb.com/title/tt21957774/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov25_2 <- bow(movie25_url2, user_agent = "educational purposes")

movie25_2 <- read_html(movie25_url2)
```

```{r}
#geting the 21th movie title to include it for the data frame.
(twentyfive_title <- sub_movie[33])

#get the reviewer's name.
(reviewer25 <- movie21 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer25 <- data.frame(Name = reviewer25))
```

```{r}
#get the reviewer's name.
(reviewer25_2 <- movie25_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer25_2 <- data.frame(Name = reviewer25_2))
```

```{r}
#combine the output into one row
(nameRev25 <- rbind(df_reviewer25,df_reviewer25_2))
```

```{r}
#get the the date of reviews
reviews_date25 <- movie25 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate25 <- data.frame(DateReview = reviews_date25))
```

```{r}
#get the the date of reviews
reviews_date25_2 <- movie25_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate25_2 <- data.frame(DateReview = reviews_date25_2))

#combine the output into one row
(dateRev25 <- rbind(df_reviewsDate25, df_reviewsDate25_2))
```

```{r}
#get the user ratings
(reviews_rating25 <- movie25 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings
(sub_reviewsRating25 <- reviews_rating25[1:50])

#split the output to get on;y the rates without the \n.
(rate_split25 <- unlist(strsplit(sub_reviewsRating25, "\\s+")))

#select only the ratings to exclude the white space
(splitRate25 <- rate_split25[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating25 <- data.frame (Rating = splitRate25))
```

```{r}
#get the user ratings
(reviews_rating25_2 <- movie25_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings 
(sub_reviewsRating25_2 <- reviews_rating25_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split25_2 <- unlist(strsplit(sub_reviewsRating25_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate25_2 <- rate_split25_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating25_2 <- data.frame (Rating = splitRate25_2))
```

```{r}
#combine into one row
(rating25 <- rbind(df_rating25,df_rating25_2))
```

```{r}
#get the contents of the reviews
(review_text25 <- movie25 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText25 <- data.frame(TextReview = review_text25))
```

```{r}
#get the contents of the reviews
review_text25_2 <- movie25_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText25_2 <- data.frame(TextReview = review_text25_2))
```

```{r}
#combine into one frame
(textRev25 <- rbind(df_reviewText25,df_reviewText25_2))
```

```{r}
#get the review title.
review_title25 <- movie25 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev25 <- review_title25[1:25])

(review_split25 <- unlist(strsplit(sub_titrev25, "\n")))

#set as data frame
(df_reviewTitle25 <- data.frame(TitleReview = review_split25))
```

```{r}
#get the review title.
review_title25_2 <- movie25_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev25_2 <- review_title25_2[1:25])

(review_split25_2 <- unlist(strsplit(sub_titrev25_2, "\n")))

#set as data frame
(df_reviewTitle25_2 <- data.frame(TitleReview = review_split25_2))
```

```{r}
#combine into one row
(titleRev25 <- rbind(df_reviewTitle25, df_reviewTitle25_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie25 <- data.frame(Title = twentyfive_title,
                        nameRev25,
                        rating25,                    
                        dateRev25,
                        textRev25,
                        titleRev25)
)
```

```{r}
library(polite)
library(rvest)

#26th movie url for the the name of the reviewer.
movie26_url <- "https://www.imdb.com/title/tt26658104/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov26 <- bow(movie26_url, user_agent = "educational purposes")

movie26 <- read_html(movie26_url)

movie26_url2 <- "https://www.imdb.com/title/tt26658104/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov26_2 <- bow(movie26_url, user_agent = "educational purposes")

movie26_2 <- read_html(movie26_url2)
```

```{r}
#geting the 26th movie title to include it for the data frame.
(twentysix_title <- sub_movie[34])

#get the reviewer's name.
(reviewer26 <- movie26 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer26 <- data.frame(Name = reviewer26))
```

```{r}
#get the reviewer's name.
(reviewer26_2 <- movie26_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer26_2 <- data.frame(Name = reviewer26_2))
```

```{r}
#combine the output into one row
(nameRev26 <- rbind(df_reviewer26,df_reviewer26_2))
```

```{r}
#get the the date of reviews
reviews_date26 <- movie26 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate26 <- data.frame(DateReview = reviews_date26))
```

```{r}
#get the the date of reviews
reviews_date26_2 <- movie26_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate26_2 <- data.frame(DateReview = reviews_date26_2))
```

```{r}
#combine the output into one row
(dateRev26 <- rbind(df_reviewsDate26, df_reviewsDate26_2))
```

```{r}
#get the user ratings
reviews_rating26 <- movie26 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings 
(sub_reviewsRating26 <- reviews_rating26[1:50])

#split the output to get only the rates without the \n.
(rate_split26 <- unlist(strsplit(sub_reviewsRating26, "\\s+")))

#select only the ratings to exclude the white space
(splitRate26 <- rate_split26[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating26 <- data.frame (Rating = splitRate26))
```

```{r}
#get the user ratings
reviews_rating26_2 <- movie26_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings
(sub_reviewsRating26_2 <- reviews_rating26_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split26_2 <- unlist(strsplit(sub_reviewsRating26_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate26_2 <- rate_split26_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating26_2 <- data.frame (Rating = splitRate26_2))
```

```{r}
#combine into one row
(rating26 <- rbind(df_rating26,df_rating26_2))
```

```{r}
#get the contents of the reviews
review_text26 <- movie26 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText26 <- data.frame(TextReview = review_text26))
```


```{r}
#get the contents of the reviews
review_text26_2 <- movie26_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText26_2 <- data.frame(TextReview = review_text26_2))
```

```{r}
#combine into one frame
(textRev26 <- rbind(df_reviewText26,df_reviewText26_2))
```

```{r}
#get the review title.
review_title26 <- movie26 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev26 <- review_title26[1:25])

(review_split26 <- unlist(strsplit(sub_titrev26, "\n")))

#set as data frame
(df_reviewTitle26 <- data.frame(TitleReview = review_split26))
```

```{r}
#get the review title.
review_title26_2 <- movie26_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev26_2 <- review_title26_2[1:25])

(review_split26_2 <- unlist(strsplit(sub_titrev26_2, "\n")))

#set as data frame
(df_reviewTitle26_2 <- data.frame(TitleReview = review_split26_2))
```

```{r}
#combine into one row
(titleRev26 <- rbind(df_reviewTitle26, df_reviewTitle26_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie26 <- data.frame(Title = twentysix_title,
                        nameRev26,
                        rating26,                    
                        dateRev26,
                        textRev26,
                        titleRev26)
)
```

```{r}
(moviesRev23456 <- rbind(df_movie23, df_movie24, df_movie25, df_movie26))
```


```{r}
library(readr)
write.csv(moviesRev23456, "IMDBmoviesReviews(7th_200).csv")

read.csv("IMDBmoviesReviews(7th_200).csv")
```


```{r}
library(polite)
library(rvest)

#27th movie url for the the name of the reviewer.
movie19_url <- "https://www.imdb.com/title/tt26047818/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov19 <- bow(movie19_url, user_agent = "educational purposes")

movie19 <- read_html(movie19_url)

movie19_url2 <- "https://www.imdb.com/title/tt26047818/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov19_2 <- bow(movie19_url2, user_agent = "educational purposes")

movie19_2 <- read_html(movie19_url2)
```

```{r}
#geting the 19th movie title to include it for the data frame.
(nineteenth_title <- sub_movie[23])

#get the reviewer's name.
reviewer19 <- movie19 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer19

#set as data frame
(df_reviewer19 <- data.frame(Name = reviewer19))
```

```{r}
#get the reviewer's name.
reviewer19_2 <- movie19_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer19_2

#set as data frame
(df_reviewer19_2 <- data.frame(Name = reviewer19_2))
```

```{r}
#combine into one row
(nameRev19 <- rbind(df_reviewer19, df_reviewer19_2)) 
```

```{r}
#get the the date of reviews
reviews_date19 <- movie19 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate19 <- data.frame(DateReview = reviews_date19))
```

```{r}
#get the the date of reviews
reviews_date19_2 <- movie19_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate19_2 <- data.frame(DateReview = reviews_date19_2))
```

```{r}
#combine into one row
(dateRev19 <- rbind(df_reviewsDate19, df_reviewsDate19_2)) 
```

```{r}
#get the user ratings
reviews_rating19 <- movie19 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating19

#subset the ratings 
(sub_reviewsRating19 <- reviews_rating19[1:50])

#split the output to get on;y the rates without the \n.
(rate_split19 <- unlist(strsplit(sub_reviewsRating19, "\\s+")))

#select only the ratings to exclude the white space
(splitRate19 <- rate_split19[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating19 <- data.frame (Rating = splitRate19))
```

```{r}
#get the user ratings
reviews_rating19_2 <- movie19_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating19_2

#subset the ratings 
(sub_reviewsRating19_2 <- reviews_rating19_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split19_2 <- unlist(strsplit(sub_reviewsRating19_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate19_2 <- rate_split19_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating19_2 <- data.frame (Rating = splitRate19_2))
```

```{r}
#combine into one row
(rating19 <- rbind(df_rating19,df_rating19_2))
```

```{r}
#get the contents of the reviews
review_text19 <- movie19 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text19

#set as data frame.
(df_reviewText19 <- data.frame(TextReview = review_text19))
```

```{r}
#get the contents of the reviews
review_text19_2 <- movie19_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text19_2

#set as data frame.
(df_reviewText19_2 <- data.frame(TextReview = review_text19_2))
```

```{r}
#cobine into one row
(textRev19 <- rbind(df_reviewText19, df_reviewText19_2))
```

```{r}
#get the review title.
review_title19 <- movie19 %>%
  html_nodes("a.title") %>%
  html_text()
review_title19

#subset the review title get only 25
(sub_titrev19 <- review_title19[1:25])

(review_split19 <- unlist(strsplit(sub_titrev19, "\n")))

#set as data frame
(df_reviewTitle19 <- data.frame(TitleReview = review_split19))
```

```{r}
#get the review title.
review_title19_2 <- movie19_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title19_2

#subset the review title get only 25
(sub_titrev19_2 <- review_title19_2[1:25])

(review_split19_2 <- unlist(strsplit(sub_titrev19_2, "\n")))
#set as data frame
(df_reviewTitle19_2 <- data.frame(TitleReview = review_split19_2))
```

```{r}
(titleRev19 <- rbind(df_reviewTitle19, df_reviewTitle19_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie19 <- data.frame(Title = nineteenth_title,
                        nameRev19,
                        rating19,                    
                        dateRev19,
                        textRev19,
                        titleRev19)
)
```

```{r}
library(polite)
library(rvest)

#20th movie url for the the name of the reviewer.
movie20_url <- "https://www.imdb.com/title/tt0094721/reviews?sort=curated&dir=desc&ratingFilter=9"
session_Mov20 <- bow(movie20_url, user_agent = "educational purposes")

movie20 <- read_html(movie20_url)

movie20_url2 <- "https://www.imdb.com/title/tt0094721/reviews?sort=curated&dir=desc&ratingFilter=8"
session_Mov20_2 <- bow(movie20_url2, user_agent = "educational purposes")

movie20_2 <- read_html(movie20_url2)
```

```{r}
#geting the 20th movie title to include it for the data frame.
(twentieth_title <- sub_movie[24])

#get the reviewer's name.
reviewer20 <- movie20 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
reviewer20

#set as data frame
(df_reviewer20 <- data.frame(Name = reviewer20))
```

```{r}
#get the reviewer's name.
(reviewer20_2 <- movie20_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer20_2 <- data.frame(Name = reviewer20_2))
```

```{r}
#combine the output into one row
(nameRev20 <- rbind(df_reviewer20,df_reviewer20_2))
```

```{r}
#get the the date of reviews
reviews_date20 <- movie20 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate20 <- data.frame(DateReview = reviews_date20))
```

```{r}
#get the the date of reviews
reviews_date20_2 <- movie20_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate20_2 <- data.frame(DateReview = reviews_date20_2))
```

```{r}
#combine the output into one row
(dateRev20 <- rbind(df_reviewsDate20, df_reviewsDate20_2))
```

```{r}
#get the user ratings
reviews_rating20 <- movie20 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()


#subset the ratings 
(sub_reviewsRating20 <- reviews_rating20[1:50])

#split the output to get on;y the rates without the \n.
(rate_split20 <- unlist(strsplit(sub_reviewsRating20, "\\s+")))

#select only the ratings to exclude the white space
(splitRate20 <- rate_split20[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating20 <- data.frame (Rating = splitRate20))
```

```{r}
#get the user ratings
reviews_rating20_2 <- movie20_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()

#subset the ratings
(sub_reviewsRating20_2 <- reviews_rating20_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split20_2 <- unlist(strsplit(sub_reviewsRating20_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate20_2 <- rate_split20_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating20_2 <- data.frame (Rating = splitRate20_2))
```

```{r}
#combine into one row
(rating20 <- rbind(df_rating20,df_rating20_2))
```

```{r}
#get the contents of the reviews
review_text20 <- movie20 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text20

#set as data frame.
(df_reviewText20 <- data.frame(TextReview = review_text20))
```

```{r}
#get the contents of the reviews
review_text20_2 <- movie20_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()
review_text20_2

#set as data frame.
(df_reviewText20_2 <- data.frame(TextReview = review_text20_2))
```

```{r}
#combine into one frame
(textRev20 <- rbind(df_reviewText20,df_reviewText20_2))
```

```{r}
#get the review title.
review_title20 <- movie20 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev20 <- review_title20[1:25])

(review_split20 <- unlist(strsplit(sub_titrev20, "\n")))

#set as data frame
(df_reviewTitle20 <- data.frame(TitleReview = review_split20))
```

```{r}
#get the review title.
review_title20_2 <- movie20_2 %>%
  html_nodes("a.title") %>%
  html_text()
review_title20_2

#subset the review title get only 25
(sub_titrev20_2 <- review_title20_2[1:25])

(review_split20_2 <- unlist(strsplit(sub_titrev20_2, "\n")))

#set as data frame
(df_reviewTitle20_2 <- data.frame(TitleReview = review_split20_2))
```

```{r}
#combine into one row
(titleRev20 <- rbind(df_reviewTitle20, df_reviewTitle20_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie20 <- data.frame(Title = twentieth_title,
                        nameRev20,
                        rating20,                    
                        dateRev20,
                        textRev20,
                        titleRev20)
)
```

```{r}
library(polite)
library(rvest)

#21 movie url for the the name of the reviewer.
movie21_url <- "https://www.imdb.com/title/tt11057302/reviews?sort=curated&dir=asc&ratingFilter=0"
session_Mov21 <- bow(movie21_url, user_agent = "educational purposes")

movie21 <- read_html(movie21_url)

movie21_url2 <- "https://www.imdb.com/title/tt11057302/reviews?sort=curated&dir=desc&ratingFilter=0"
session_Mov21_2 <- bow(movie21_url2, user_agent = "educational purposes")

movie21_2 <- read_html(movie21_url2)
```

```{r}
#geting the 21th movie title to include it for the data frame.
(twentyone_title <- sub_movie[25])

#get the reviewer's name.
(reviewer21 <- movie21 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer21 <- data.frame(Name = reviewer21))
```

```{r}
#get the reviewer's name.
(reviewer21_2 <- movie21_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer21_2 <- data.frame(Name = reviewer21_2))
```

```{r}
#combine the output into one row
(nameRev21 <- rbind(df_reviewer21,df_reviewer21_2))
```

```{r}
#get the the date of reviews
reviews_date21 <- movie21 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate21 <- data.frame(DateReview = reviews_date21))
```

```{r}
#get the the date of reviews
reviews_date21_2 <- movie21_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate21_2 <- data.frame(DateReview = reviews_date21_2))

#combine the output into one row
(dateRev21 <- rbind(df_reviewsDate21, df_reviewsDate21_2))
```

```{r}
#get the user ratings
(reviews_rating21 <- movie21 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings
(sub_reviewsRating21 <- reviews_rating21[1:50])

#split the output to get on;y the rates without the \n.
(rate_split21 <- unlist(strsplit(sub_reviewsRating21, "\\s+")))

#select only the ratings to exclude the white space
(splitRate21 <- rate_split21[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating21 <- data.frame (Rating = splitRate21))
```

```{r}
#get the user ratings
(reviews_rating21_2 <- movie21_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text())

#subset the ratings 
(sub_reviewsRating21_2 <- reviews_rating21_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split21_2 <- unlist(strsplit(sub_reviewsRating21_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate21_2 <- rate_split21_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating21_2 <- data.frame (Rating = splitRate21_2))
```

```{r}
#combine into one row
(rating21 <- rbind(df_rating21,df_rating21_2))
```

```{r}
#get the contents of the reviews
(review_text21 <- movie21 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text())

#set as data frame.
(df_reviewText21 <- data.frame(TextReview = review_text21))
```

```{r}
#get the contents of the reviews
review_text21_2 <- movie21_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText21_2 <- data.frame(TextReview = review_text21_2))
```

```{r}
#combine into one frame
(textRev21 <- rbind(df_reviewText21,df_reviewText21_2))
```

```{r}
#get the review title.
review_title21 <- movie21 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev21 <- review_title21[1:25])

(review_split21 <- unlist(strsplit(sub_titrev21, "\n")))

#set as data frame
(df_reviewTitle21 <- data.frame(TitleReview = review_split21))
```

```{r}
#get the review title.
review_title21_2 <- movie21_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev21_2 <- review_title21_2[1:25])

(review_split21_2 <- unlist(strsplit(sub_titrev21_2, "\n")))

#set as data frame
(df_reviewTitle21_2 <- data.frame(TitleReview = review_split21_2))
```

```{r}
#combine into one row
(titleRev21 <- rbind(df_reviewTitle21, df_reviewTitle21_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie21 <- data.frame(Title = twentyone_title,
                        nameRev21,
                        rating21,                    
                        dateRev21,
                        textRev21,
                        titleRev21)
)
```

```{r}
library(polite)
library(rvest)

#22 movie url for the the name of the reviewer.
movie22_url <- "https://www.imdb.com/title/tt0087332/reviews?sort=curated&dir=desc&ratingFilter=7"
session_Mov22 <- bow(movie22_url, user_agent = "educational purposes")

movie22 <- read_html(movie22_url)

movie22_url2 <- "https://www.imdb.com/title/tt0087332/reviews?sort=curated&dir=desc&ratingFilter=10"
session_Mov22_2 <- bow(movie22_url, user_agent = "educational purposes")

movie22_2 <- read_html(movie22_url2)
```

```{r}
#geting the 22th movie title to include it for the data frame.
(twentytwo_title <- sub_movie[27])

#get the reviewer's name.
(reviewer22 <- movie22 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer22 <- data.frame(Name = reviewer22))
```

```{r}
#get the reviewer's name.
(reviewer22_2 <- movie22_2 %>%
  html_nodes("span.display-name-link") %>%
  html_text())

#set as data frame
(df_reviewer22_2 <- data.frame(Name = reviewer22_2))
```

```{r}
#combine the output into one row
(nameRev22 <- rbind(df_reviewer22,df_reviewer22_2))
```

```{r}
#get the the date of reviews
reviews_date22 <- movie22 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame
(df_reviewsDate22 <- data.frame(DateReview = reviews_date22))
```

```{r}
#get the the date of reviews
reviews_date22_2 <- movie22_2 %>%
  html_nodes("span.review-date") %>%
  html_text()

#set as data frame 
(df_reviewsDate22_2 <- data.frame(DateReview = reviews_date22_2))
```

```{r}
#combine the output into one row
(dateRev22 <- rbind(df_reviewsDate22, df_reviewsDate22_2))
```

```{r}
#get the user ratings
reviews_rating22 <- movie22 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating22

#subset the ratings 
(sub_reviewsRating22 <- reviews_rating22[1:50])

#split the output to get only the rates without the \n.
(rate_split22 <- unlist(strsplit(sub_reviewsRating22, "\\s+")))

#select only the ratings to exclude the white space
(splitRate22 <- rate_split22[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating22 <- data.frame (Rating = splitRate22))
```

```{r}
#get the user ratings
reviews_rating22_2 <- movie22_2 %>%
  html_nodes("div.ipl-ratings-bar") %>%
  html_text()
reviews_rating22_2

#subset the ratings
(sub_reviewsRating22_2 <- reviews_rating22_2[1:50])

#split the output to get on;y the rates without the \n.
(rate_split22_2 <- unlist(strsplit(sub_reviewsRating22_2, "\\s+")))

#select only the ratings to exclude the white space
(splitRate22_2 <- rate_split22_2[c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50)])

#set as data frame
(df_rating22_2 <- data.frame (Rating = splitRate22_2))
```

```{r}
#combine into one row
(rating22 <- rbind(df_rating22,df_rating22_2))
```

```{r}
#get the contents of the reviews
review_text22 <- movie22 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText22 <- data.frame(TextReview = review_text22))
```


```{r}
#get the contents of the reviews
review_text22_2 <- movie22_2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#set as data frame.
(df_reviewText22_2 <- data.frame(TextReview = review_text22_2))
```

```{r}
#combine into one frame
(textRev22 <- rbind(df_reviewText22,df_reviewText22_2))
```

```{r}
#get the review title.
review_title22 <- movie22 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev22 <- review_title22[1:25])

(review_split22 <- unlist(strsplit(sub_titrev22, "\n")))

#set as data frame
(df_reviewTitle22 <- data.frame(TitleReview = review_split22))
```

```{r}
#get the review title.
review_title22_2 <- movie22_2 %>%
  html_nodes("a.title") %>%
  html_text()

#subset the review title get only 25
(sub_titrev22_2 <- review_title22_2[1:25])

(review_split22_2 <- unlist(strsplit(sub_titrev22_2, "\n")))

#set as data frame
(df_reviewTitle22_2 <- data.frame(TitleReview = review_split22_2))
```

```{r}
#combine into one row
(titleRev22 <- rbind(df_reviewTitle22, df_reviewTitle22_2))
```

```{r}
#combined the outputs of the first movie in a data frame
(df_movie22 <- data.frame(Title = twentytwo_title,
                        nameRev22,
                        rating22,                    
                        dateRev22,
                        textRev22,
                        titleRev22)
)
```

```{r}
(moviesRev1920122 <- rbind(df_movie19, df_movie20, df_movie21, df_movie22))
```


```{r}
write.csv(moviesRev1920122, "IMDBmoviesReviews(6th_200).csv")

read.csv("IMDBmoviesReviews(6th_200).csv")











